# zorluk: kolay, orta, zor
LGS_KONULAR = {
    "Matematik": [
        {"donem": 1, "konu": "Çarpanlar ve Katlar", "zorluk": "kolay", "aciklama": "Pozitif tam sayıların çarpanları, EBOB-EKOK, aralarında asallık."},
        {"donem": 1, "konu": "Veri Analizi", "zorluk": "kolay", "aciklama": "Çizgi ve sütun grafikleri, daire grafiği dönüşümleri."},
        {"donem": 1, "konu": "Basit Olayların Olma Olasılığı", "zorluk": "kolay", "aciklama": "Olası durumlar; daha fazla, daha az veya eşit olasılıklı olaylar."},
        {"donem": 1, "konu": "Üslü İfadeler", "zorluk": "orta", "aciklama": "Tam sayıların üslü kuvvetleri, işlemler, bilimsel gösterim."},
        {"donem": 2, "konu": "Doğrusal Denklemler", "zorluk": "orta", "aciklama": "Birinci dereceden bir bilinmeyenli denklemler, koordinat sistemi, eğim."},
        {"donem": 2, "konu": "Eşitsizlikler", "zorluk": "orta", "aciklama": "Birinci dereceden bir bilinmeyenli eşitsizliklerin gösterimi ve çözümü."},
        {"donem": 2, "konu": "Dönüşüm Geometrisi", "zorluk": "orta", "aciklama": "Öteleme, yansıma ve ardışık dönüşümler."},
        {"donem": 1, "konu": "Kareköklü İfadeler", "zorluk": "zor", "aciklama": "Tam kare sayılar, kareköklü ifadelerde işlemler, gerçek sayılar."},
        {"donem": 1, "konu": "Cebirsel İfadeler ve Özdeşlikler", "zorluk": "zor", "aciklama": "Çarpma, tam kare ve iki kare farkı, çarpanlara ayırma."},
        {"donem": 2, "konu": "Üçgenler", "zorluk": "zor", "aciklama": "Kenarortay, açıortay, yükseklik, üçgen eşitsizliği, Pisagor."},
        {"donem": 2, "konu": "Eşlik ve Benzerlik", "zorluk": "zor", "aciklama": "Eş ve benzer şekillerin kenar-açı ilişkileri, benzerlik oranı."},
        {"donem": 2, "konu": "Geometrik Cisimler", "zorluk": "zor", "aciklama": "Dik prizma, silindir, piramit ve koni; yüzey alanı ve hacim."},
    ],
    "Türkçe": [
        {"donem": 1, "konu": "Sözcükte ve Söz Gruplarında Anlam", "zorluk": "kolay", "aciklama": "Gerçek, mecaz, terim anlam, deyimler ve atasözleri."},
        {"donem": 1, "konu": "Yazım Kuralları ve Noktalama", "zorluk": "kolay", "aciklama": "Yazım kuralları ve noktalama işaretleri."},
        {"donem": 1, "konu": "Cümlede Anlam", "zorluk": "orta", "aciklama": "Öznel-nesnel, neden-sonuç, amaç-sonuç, koşul, örtülü anlam."},
        {"donem": 1, "konu": "Cümlenin Ögeleri", "zorluk": "orta", "aciklama": "Özne, yüklem, nesne ve tümleçler."},
        {"donem": 2, "konu": "Paragrafta Anlam ve Metin Analizi", "zorluk": "orta", "aciklama": "Ana düşünce, yardımcı düşünce, metin türleri ve söz sanatları."},
        {"donem": 2, "konu": "Cümle Çeşitleri", "zorluk": "orta", "aciklama": "Yüklemin türüne, yerine, anlamına ve yapısına göre cümleler."},
        {"donem": 2, "konu": "Anlatım Bozuklukları", "zorluk": "orta", "aciklama": "Anlamsal ve yapısal anlatım bozuklukları."},
        {"donem": 1, "konu": "Fiilimsiler", "zorluk": "zor", "aciklama": "İsim-fiil, sıfat-fiil, zarf-fiil."},
        {"donem": 2, "konu": "Fiilde Çatı", "zorluk": "zor", "aciklama": "Etken-edilgen, geçişli-geçişsiz çatılar."},
        {"donem": 2, "konu": "Görsel Okuma ve Sözel Mantık", "zorluk": "zor", "aciklama": "Grafik, tablo, harita yorumlama ve muhakeme."},
    ],
    "Fen Bilimleri": [
        {"donem": 1, "konu": "Mevsimler ve İklim", "zorluk": "kolay", "aciklama": "Mevsimlerin oluşumu, iklim ve hava hareketleri."},
        {"donem": 1, "konu": "Basınç", "zorluk": "orta", "aciklama": "Katı, sıvı ve gaz basıncı, günlük yaşam örnekleri."},
        {"donem": 2, "konu": "Basit Makineler", "zorluk": "orta", "aciklama": "Kaldıraç, makara, palanga, eğik düzlem, çıkrık, vida, dişli ve kasnak."},
        {"donem": 2, "konu": "Enerji Dönüşümleri ve Çevre Bilimi", "zorluk": "orta", "aciklama": "Besin zinciri, fotosentez, solunum, madde döngüleri."},
        {"donem": 1, "konu": "DNA ve Genetik Kod", "zorluk": "zor", "aciklama": "DNA, kalıtım, mutasyon, modifikasyon, adaptasyon, biyoteknoloji."},
        {"donem": 1, "konu": "Madde ve Endüstri", "zorluk": "zor", "aciklama": "Periyodik sistem, tepkimeler, asit-baz, ısı, kimya endüstrisi."},
        {"donem": 2, "konu": "Elektrik Yükleri ve Elektrik Enerjisi", "zorluk": "zor", "aciklama": "Elektrik yükleri, elektriklenme, elektroskop, enerji dönüşümü."},
    ],
    "T.C. İnkılap Tarihi": [
        {"donem": 1, "konu": "Bir Kahraman Doğuyor", "zorluk": "kolay", "aciklama": "Atatürk'ün hayatı ve yetiştiği dönem."},
        {"donem": 2, "konu": "Atatürk'ün Ölümü ve Sonrası", "zorluk": "kolay", "aciklama": "II. Dünya Savaşı ve Türkiye'ye etkileri."},
        {"donem": 1, "konu": "Milli Uyanış", "zorluk": "orta", "aciklama": "I. Dünya Savaşı, cemiyetler, genelgeler ve kongreler."},
        {"donem": 2, "konu": "Demokratikleşme Adımları", "zorluk": "orta", "aciklama": "Çok partili hayat denemeleri ve suikast girişimi."},
        {"donem": 2, "konu": "Atatürk Dönemi Türk Dış Politikası", "zorluk": "orta", "aciklama": "Dış politikanın ilkeleri ve Hatay'ın katılması."},
        {"donem": 1, "konu": "Ya İstiklal Ya Ölüm", "zorluk": "zor", "aciklama": "Cepheler, Mudanya ve Lozan."},
        {"donem": 2, "konu": "Atatürkçülük ve Çağdaşlaşan Türkiye", "zorluk": "zor", "aciklama": "Atatürk ilkeleri ve inkılaplar."},
    ],
    "Din Kültürü": [
        {"donem": 1, "konu": "Zekât ve Sadaka", "zorluk": "kolay", "aciklama": "Paylaşma, zekât, sadaka, Hz. Şuayb, Maûn suresi."},
        {"donem": 1, "konu": "Hz. Muhammed'in Örnekliği", "zorluk": "kolay", "aciklama": "Doğruluk, adalet, istişare, cesaret, Kureyş suresi."},
        {"donem": 1, "konu": "Kader İnancı", "zorluk": "orta", "aciklama": "Kader, kaza, irade ve Hz. Musa."},
        {"donem": 1, "konu": "Din ve Hayat", "zorluk": "orta", "aciklama": "Can, nesil, akıl, mal ve din emniyeti, Asr suresi."},
        {"donem": 2, "konu": "Kur'an-ı Kerim ve Özellikleri", "zorluk": "orta", "aciklama": "Kur'an'ın ana konuları ve temel özellikleri."},
    ],
    "İngilizce": [
        {"donem": 1, "konu": "Friendship", "zorluk": "kolay", "aciklama": "Dostluk, davet etme, kabul ve reddetme."},
        {"donem": 1, "konu": "Teen Life", "zorluk": "kolay", "aciklama": "Gençlik, sıklık zarfları, ilgi ve tercihler."},
        {"donem": 1, "konu": "In the Kitchen", "zorluk": "kolay", "aciklama": "Mutfak, tarif ve işlem sırası."},
        {"donem": 1, "konu": "On the Phone", "zorluk": "kolay", "aciklama": "Telefonda konuşma ve mesaj bırakma."},
        {"donem": 1, "konu": "The Internet", "zorluk": "orta", "aciklama": "İnternet kullanımı, güvenlik ve terimler."},
        {"donem": 1, "konu": "Adventures", "zorluk": "orta", "aciklama": "Macera, ekstrem spor ve karşılaştırma."},
        {"donem": 2, "konu": "Tourism", "zorluk": "orta", "aciklama": "Turizm, geçmiş deneyimler, tatil tercihleri."},
        {"donem": 2, "konu": "Chores", "zorluk": "zor", "aciklama": "Ev işleri, must ve have to."},
        {"donem": 2, "konu": "Science", "zorluk": "zor", "aciklama": "Bilim, geçmiş ve şimdiki zaman."},
        {"donem": 2, "konu": "Natural Forces", "zorluk": "zor", "aciklama": "Doğal afetler ve geleceğe yönelik tahminler."},
    ],
}
