# Sınıf düzeyine göre okuma kitapları: (ad, yazar, yayınevi, sayfa)
OKUMA_KITAPLARI: dict[int, list[tuple[str, str, str, int]]] = {
    5: [
        ("Bana Derler Küp Cadısı", "Nur İçözü", "Altın Kitaplar", 120),
        ("Karne Hediyesi At Kestanesi", "Miyase Sertbarut", "Altın Kitaplar", 128),
        ("Yürek Dede ile Padişah", "Cahit Zarifoğlu", "Beyan Çocuk", 87),
        ("Sadako", "Eleanor Coerr", "Beyaz Balina Yayınları", 100),
        ("Hachiko", "Leslea Newman", "Beyaz Balina Yayınları", 152),
        ("Dünyayı Bisikletle Dolaşan Çocuk", "Alastair Humphreys", "Beyaz Balina Yayınları", 128),
        ("Matematik Romanı: Şifrelerin Peşinde İstanbul", "Hasan Topdemir", "Beyaz Balina Yayınları", 104),
        ("Yüz Elbisenin Sırrı", "Eleanor Estes", "Beyaz Balina Yayınları", 96),
        ("Kum Saati", "Fatih Tuncay", "Bilgi Yayınevi", 128),
        ("Zaman Bisikleti", "Bilgin Adalı", "Can Çocuk Yayınları", 128),
        ("Domates Saçlı Kız", "Sevim Ak", "Can Çocuk Yayınları", 192),
        ("Martıya Uçmayı Öğreten Kedi", "Luis Sepúlveda", "Can Çocuk Yayınları", 128),
        ("Büyük Atatürk'ten Küçük Öyküler 1", "Süleyman Bulut", "Can Çocuk Yayınları", 148),
        ("Kitaplardan Korkan Çocuk", "Susanna Tamaro", "Can Çocuk Yayınları", 44),
        ("Küçük Kara Balık", "Samed Behrengi", "Can Çocuk Yayınları", 56),
        ("Uçan Sınıf", "Erich Kästner", "Can Çocuk Yayınları", 188),
        ("Yeşil Kafalar 1", "Tuğba Coşkuner", "Cezve Çocuk", 200),
        ("Yeşil Kafalar 2", "Tuğba Coşkuner", "Cezve Çocuk", 192),
        ("Gıdıklanan Kitap", "Mavisel Yener", "Doğan Egmont Çocuk Kitapları", 136),
        ("Cingo", "Şermin Yaşar", "Doğan Egmont Çocuk Kitapları", 188),
        ("Oh Ne Ala Memleket", "Şermin Yaşar", "Doğan Egmont Çocuk Kitapları", 168),
        ("Sözcüklerin Kamera Arkası", "Ferhat Taştekin", "Timaş Genç", 144),
        ("Güzel Ülkem Türkiye 1", "Metin Özdamarlar", "Eğlenceli Bilgi", 176),
        ("Ballı Çörek Kafeteryası", "Zeynep Cemali", "Günışığı Kitaplığı", 240),
        ("Dedem Bir Kiraz Ağacı", "Angela Nanetti", "Günışığı Kitaplığı", 160),
        ("Yaşasın Ç Harfi Kardeşliği", "Behiç Ak", "Günışığı Kitaplığı", 104),
        ("Postayla Gelen Deniz Kabuğu", "Behiç Ak", "Günışığı Kitaplığı", 160),
        ("Haritada Kaybolmak", "Vladimir Tumanov", "Günışığı Kitaplığı", 228),
        ("Kraliçeyi Kurtarmak", "Vladimir Tumanov", "Günışığı Kitaplığı", 180),
        ("Çatıdaki Gezegen", "Behiç Ak", "Günışığı Kitaplığı", 180),
        ("Ağaçtaki Ev", "Bianca Pitzorno", "Günışığı Kitaplığı", 120),
        ("Eyvah Kitap", "Mine Soysal", "Günışığı Kitaplığı", 127),
        ("Son Adanın Çocukları", "Zülfü Livaneli", "İnkılap Kitabevi", 164),
        ("Mutlukent'in Yöneticisi", "Emin Özdemir", "Kök Yayıncılık", 135),
        ("Deyim mi Demeyim mi", "Melek Çe", "Nar Çocuk Yayınları", 200),
        ("Kayıp Küp", "Mehmet Vicdan", "Paragrafın Şifresi Kitapçılık", 96),
        ("Şamatalı Köy", "Astrid Lindgren", "Pegasus Çocuk Yayınları", 104),
        ("Dünyayı Sırtında Taşıyan Balık", "Özgür Balpınar", "Timaş Genç", 176),
        ("Göğü Yere İndirelim", "Özgür Balpınar", "Timaş Genç", 152),
        ("Düşler Atlası", "Özgür Balpınar", "Timaş Genç", 160),
        ("Zerdali Dedemle Bir Yıl", "Yaşar Bayraktar", "Timaş İlk Genç", 144),
        ("Mırıldanan Çocuk", "Gabriele Clima", "Timaş İlk Genç", 184),
        ("Yankılı Kayalar", "Ahmet Yılmaz Boyunağa", "Timaş İlk Genç", 112),
        ("Bir Küçük Osmancık Vardı", "Hasan Nail Canat", "Timaş İlk Genç", 128),
        ("Çiçek Ekspresi", "Özgür Balpınar", "Timaş İlk Genç", 120),
        ("Yuan Huan'ın Kulübesi", "Miyase Sertbarut", "Tudem", 136),
        ("Gülen Sakız Ağacı", "Koray Avcı Çakman", "Tudem", 112),
        ("Ölümsüz Aile", "Natalie Babbitt", "Türkiye İş Bankası Kültür Yayınları", 108),
        ("Olmayan Ülke", "Ahmet Ümit", "Yapı Kredi Yayınları", 148),
        ("Masal Masal İçinde", "Ahmet Ümit", "Yapı Kredi Yayınları", 144),
    ],
    6: [
        ("Fadiş", "Gülten Dayıoğlu", "Altın Kitaplar", 160),
        ("Ganga", "Gülten Dayıoğlu", "Altın Kitaplar", 191),
        ("Midos Kartalı'nın Gözleri", "Gülten Dayıoğlu", "Altın Kitaplar", 172),
        ("Harflere Ne Oldu?", "Sezer Ün", "Beyaz Balina Yayınları", 144),
        ("Şifrelerin Peşinde Göbekli Tepe", "Hasan Topdemir", "Beyaz Balina Yayınları", 112),
        ("Köprü Altındaki Aile", "Natalie Savage Carlson", "Beyaz Balina Yayınları", 115),
        ("Misko ve Beşinci Hazine", "Eleanor Coerr", "Beyaz Balina Yayınları", 100),
        ("Karamelli Akide Şekeri", "Mavisel Yener", "Bilgi Yayınevi", 104),
        ("Dolunay Dedektifleri İz Peşinde", "Mavisel Yener", "Bilgi Yayınevi", 136),
        ("Büyük Atatürk'ten Küçük Öyküler 2", "Süleyman Bulut", "Can Çocuk Yayınları", 152),
        ("Küçük Prens", "Antoine de Saint-Exupéry", "Can Çocuk Yayınları", 112),
        ("Charlie'nin Çikolata Fabrikası", "Roald Dahl", "Can Çocuk Yayınları", 208),
        ("Vanilya Kokulu Mektuplar", "Sevim Ak", "Can Çocuk Yayınları", 128),
        ("Matilda", "Roald Dahl", "Can Çocuk Yayınları", 256),
        ("Yeşil Kafalar 3: Macera Ekspresi", "Tuğba Coşkuner", "Cezve Çocuk", 176),
        ("Arkadaşıma Veda", "Zülfü Livaneli", "Doğan Egmont Çocuk Kitapları", 172),
        ("Martı Jonathan Livingston", "Richard Bach", "Epsilon", 152),
        ("Tuhaf Bilimler Akademisi", "Şöhret Doğruyol Sağbaş", "Epsilon", 168),
        ("Masalistanbul 1", "Figen Yaman Coşar", "Erdem Çocuk", 192),
        ("Çılgın Mucitler", "Yusuf Asal", "Genç Nesil", 73),
        ("Patenli Kız", "Zeynep Cemali", "Günışığı Kitaplığı", 200),
        ("Galata'nın Tembel Martısı", "Behiç Ak", "Günışığı Kitaplığı", 92),
        ("Çatıdaki Gezegen", "Behiç Ak", "Günışığı Kitaplığı", 180),
        ("Düşler Sirki", "Angela Nanetti", "Günışığı Kitaplığı", 144),
        ("Bulutlara Şiir Yazan Çocuk", "Behiç Ak", "Günışığı Kitaplığı", 160),
        ("Bunun Adı Findel", "Andrew Clements", "Günışığı Kitaplığı", 112),
        ("Bataklığın Kıyısındaki Ev", "Yeşim Saygın Armutak", "Günışığı Kitaplığı", 168),
        ("Miguel", "Alfredo Gómez Cerdá", "İletişim Yayınları", 128),
        ("Göl Çocukları", "İbrahim Örs", "Nemesis Çocuk", 128),
        ("Çılgın Mucitler", "Yusuf Asal", "Nesil Çocuk Yayınları", 176),
        ("Şimdiki Çocuklar Harika", "Aziz Nesin", "Nesin Yayınevi", 224),
        ("Sihirbazın Kuyruğu", "Aytül Akal", "Redhouse Kidz Yayınları", 136),
        ("Dedemin Bakkalı: Çırak", "Şermin Yaşar", "Taze Kitap", 160),
        ("Abartma Tozu", "Şermin Yaşar", "Taze Kitap", 160),
        ("Yeryüzünün Kalbi", "Özgür Balpınar", "Timaş Genç", 216),
        ("Yeşil Adanın Çocukları", "Havva Tekin", "Timaş Genç", 160),
        ("İçimdeki Müzik", "Sharon M. Draper", "Timaş Genç", 256),
        ("Hayal Kurmaya Cesaret Eden Köpek", "Sun-Mi Hwang", "Timaş Genç", 120),
        ("Macera Adası", "Ahmet Yılmaz Boyunağa", "Timaş İlk Genç", 96),
        ("Robit 1", "Shane Hegarty", "Timaş İlk Genç", 240),
        ("Gelecek Ekspresi", "Özgür Balpınar", "Timaş İlk Genç", 112),
        ("Ayasofya'da Bir Gece", "Rana Demiriz", "Timaş Yayınları", 192),
        ("Çöp Plaza", "Miyase Sertbarut", "Tudem", 152),
        ("Süper Gazeteciler 1", "Aytül Akal", "Tudem", 192),
        ("Çizgili Pijamalı Çocuk", "John Boyne", "Tudem", 208),
        ("Sisin Sakladıkları", "Miyase Sertbarut", "Tudem", 224),
        ("Gülen Sakız Ağacı", "Koray Avcı Çakman", "Tudem", 112),
        ("Almarpa'nın Gizemi", "Koray Avcı Çakman", "Tudem", 168),
        ("Issız Adanın Kralı", "Michael Morpurgo", "Tudem", 152),
        ("Badem Operasyonu", "Melek Çe", "Uğurböceği Yayınları", 231),
    ],
    7: [
        ("Okul Radyosu Yayında", "Ülker Kurtcan", "Abm Yayınevi", 195),
        ("Gökyüzündeki Mor Bulutlar", "Gülten Dayıoğlu", "Altın Kitaplar", 192),
        ("Işın Çağı Çocukları", "Gülten Dayıoğlu", "Altın Kitaplar", 128),
        ("Sınıftan Yükselen Sesler", "Rob Buyea", "Altın Kitaplar", 272),
        ("Petey", "Ben Mikaelsen", "Beyaz Balina Yayınları", 272),
        ("Kırık Çömlek Parçası", "Linda Sue Park", "Beyaz Balina Yayınları", 168),
        ("Suya Kavuşuncaya Dek", "Linda Sue Park", "Beyaz Balina Yayınları", 136),
        ("Can Dostum", "Walt Morey", "Beyaz Balina Yayınları", 233),
        ("Ada", "Theodore Taylor", "Beyaz Balina Yayınları", 136),
        ("Dolunay Dedektifleri 2", "Mavisel Yener", "Bilgi Yayınevi", 168),
        ("Sakız Kızın Günleri", "Sevim Ak", "Can Çocuk Yayınları", 128),
        ("Hamam mı? Tamam mı?", "Salih Uyan", "Carpediem Kitap", 144),
        ("Çok Normal", "Recep Özkul", "Çınaraltı Yayıncılık", 160),
        ("Feo ve Kurt", "Katherine Rundell", "Domingo Yayınevi", 288),
        ("Gökyüzü Çocukları", "Katherine Rundell", "Domingo Yayınevi", 280),
        ("Kara Oklar Çetesi Büyük Macera", "Ahmet Şerif İzgören", "Elma Yayınevi", 296),
        ("Esrarengiz Duman", "Aytül Akal", "Fom Kitap", 192),
        ("Zaman Hırsızı", "Clive Barker", "Günışığı Kitaplığı", 223),
        ("Suda Kaybolmak", "Vladimir Tumanov", "Günışığı Kitaplığı", 240),
        ("Garajdaki Giz", "David Almond", "Günışığı Kitaplığı", 199),
        ("Ateşten Kaçmak", "Vladimir Tumanov", "Günışığı Kitaplığı", 212),
        ("Gezginler Okulu", "Mavisel Yener", "İndigo Kitap", 198),
        ("Enno ya da Asfalttaki Karahindiba", "Astrid Frank", "Kırmızı Kedi Çocuk", 144),
        ("Matilda Etkisi", "Ellie Irving", "Martı Yayınları", 272),
        ("Çocuk Kalbi", "Edmondo De Amicis", "Nar Çocuk Yayınları", 332),
        ("Marka Benim", "İmran Aksoy", "Nar Çocuk Yayınları", 176),
        ("Cennet Kapısı Çanakkale", "Yusuf Dursun", "Nar Çocuk Yayınları", 240),
        ("İnsan Ne ile Yaşar?", "Lev N. Tolstoy", "Panama Yayıncılık", 176),
        ("Babaannem Geri Döndü", "Şermin Yaşar", "Taze Kitap", 160),
        ("Kafası Karışıklar Kulübü", "Juno Dawson", "Timaş Genç", 208),
        ("Limon Kütüphanesi", "Jo Cotterill", "Timaş Genç", 192),
        ("Kiraz Ağacıyla Aramızdaki Mesafe", "Paola Peretti", "Timaş Genç", 208),
        ("Kendine Ait Bir Ada", "Sally Nicholls", "Timaş Genç", 176),
        ("İçimdeki Melodi", "Sharon M. Draper", "Timaş Genç", 320),
        ("Eyvah Sorular Kayboldu", "Orhan Kenan", "Timaş İlk Genç", 160),
        ("Bir Tür Kıvılcım", "Elle McNicoll", "Timaş İlk Genç", 208),
        ("Robit 2", "Shane Hegarty", "Timaş İlk Genç", 240),
        ("Mavi Kanatlar", "Jef Aerts", "Timaş İlk Genç", 232),
        ("Paradokya Adalet Yıldızı ve Kayıp Pusula", "Cem Gülbent", "Timaş Yayınları", 368),
        ("Mutluluk Sokağı", "Ferda İzbudak Akıncı", "Tudem", 200),
        ("Savaş Atı", "Michael Morpurgo", "Tudem", 184),
        ("Kayıp Kitaplıktaki İskelet", "Mavisel Yener", "Tudem", 208),
        ("Kırmızı Arabanın Hayaleti", "Aytül Akal", "Tudem", 208),
        ("Mavi Zamanlar", "Mavisel Yener", "Tudem", 208),
        ("Kimsin Sen", "Miyase Sertbarut", "Tudem", 128),
        ("Kuş Olsam Evime Uçsam", "Güzin Öztürk", "Tudem", 120),
        ("Kapiland'ın Kobayları", "Miyase Sertbarut", "Tudem", 216),
        ("Çöplük", "Andy Mulligan", "Tudem", 216),
        ("Süper Gazeteciler 2", "Aytül Akal", "Tudem", 216),
        ("Söğüdün Son Yaprağı Çanakkale", "Yusuf Duru", "Yazıgen", 176),
    ],
    8: [
        ("Mo'nun Gizemi", "Gülten Dayıoğlu", "Altın Kitaplar", 288),
        ("Sekizinci Renk", "Gülten Dayıoğlu", "Altın Kitaplar", 398),
        ("Dört Kardeştiler", "Gülten Dayıoğlu", "Altın Kitaplar", 160),
        ("Esrarengiz Kelimeler", "Almila Aydın", "Altın Kitaplar", 224),
        ("Rüzgârı Dizginleyen Çocuk", "William Kamkwamba", "Beyaz Balina Yayınları", 264),
        ("İyi Geceler Bay Tom", "Michelle Magorian", "Beyaz Balina Yayınları", 404),
        ("Yasak Dağın Laneti", "Elise Broach", "Beyaz Balina Yayınları", 233),
        ("Kuklacı Çocuk", "Eva Weaver", "Beyaz Balina Yayınları", 432),
        ("Suna'nın Serçeleri", "Gülten Dayıoğlu", "Altın Kitaplar", 176),
        ("Uçurtma Avcıları", "Linda Sue Park", "Beyaz Balina Yayınları", 144),
        ("Demiryolu Çocukları", "Edith Nesbit", "Bilgi Yayınevi", 244),
        ("Az Buçuk Teo", "Sevim Ak", "Can Çocuk Yayınları", 208),
        ("Beyaz Yele", "René Guillot", "Can Çocuk Yayınları", 118),
        ("Hayvan Çiftliği", "George Orwell", "Can Yayınları", 152),
        ("Simyacı", "Paulo Coelho", "Can Yayınları", 184),
        ("Satranç", "Stefan Zweig", "Can Yayınları", 71),
        ("Uzun Hikâye", "Mustafa Kutlu", "Dergâh Yayınları", 115),
        ("Mucizeleri Saymak", "Holly Goldberg Sloan", "Domingo Yayınevi", 328),
        ("Kıbrıs: Aziz Barnabas'ın Sırrı", "Ahmet Şerif İzgören", "Elma Yayınevi", 232),
        ("Sokakta Tek Başına", "Ayhan Bozfırat", "Günışığı Kitaplığı", 180),
        ("Kâğıt Uçakla Macera", "Christine Nöstlinger", "Günışığı Kitaplığı", 252),
        ("Beyaz Diş", "Jack London", "İskele Yayıncılık", 175),
        ("Halime Kaptan", "Rıfat Ilgaz", "İş Bankası Kültür Yayınları", 197),
        ("Nutuk", "Mustafa Kemal Atatürk", "İş Bankası Kültür Yayınları", 599),
        ("İki Dirhem Bir Çekirdek", "İskender Pala", "Kapı Yayınları", 212),
        ("Eğitim Koçu Kırmızı Karınca", "Mehmet Ali Çiçekçi", "Kırmızı Karınca Yayınları", 323),
        ("Beyaz Zambaklar Ülkesinde", "Grigoriy Petrov", "Koridor Yayıncılık", 157),
        ("Sunguroğlu", "Yavuz Bahadıroğlu", "Nesil Yayınları", 656),
        ("Sol Ayağım", "Christy Brown", "Nora Kitap", 192),
        ("Beyaz Gemi", "Cengiz Aytmatov", "Ötüken Neşriyat", 168),
        ("Benim Küçük Dostlarım", "Halide Nusret Zorlutuna", "Panama Yayıncılık", 160),
        ("Mucize", "R. J. Palacio", "Pegasus Yayınları", 336),
        ("Momo", "Michael Ende", "Pegasus Yayınları", 304),
        ("Küçük Ağacın Eğitimi", "Forrest Carter", "Say Yayınları", 280),
        ("Önce Çocuklar Düşledi", "Mavisel Yener", "Tarih Vakfı Yayınları", 128),
        ("Sarayda Bir Yıl", "Rana Demiriz", "Timaş Genç", 256),
        ("Liste", "Patricia Forde", "Timaş Genç", 368),
        ("Çöpçüler", "Darren Simpson", "Timaş Genç", 320),
        ("Beyaz Odadaki Çocuk", "Karl Olsberg", "Timaş Genç", 304),
        ("Son Kelime: Liste 2", "Patricia Forde", "Timaş Genç", 288),
        ("Canım Arkadaşım", "Özgür Balpınar", "Timaş Genç", 184),
        ("Emilia Ağaçta", "Bernhard Hagemann", "Timaş Genç", 144),
        ("Robit 3", "Shane Hegarty", "Timaş İlk Genç", 224),
        ("Zombili Mombili Roman", "Aytül Akal", "Tudem", 216),
        ("Hayal Sözleşmesi", "Dilek Yardımcı", "Tudem", 216),
        ("Kayıp Zamanlar", "Michael Morpurgo", "Tudem", 192),
        ("Süper Gazeteciler 3", "Aytül Akal", "Tudem", 216),
        ("Hayallerin Ötesinde", "Dilek Yardımcı", "Tudem", 248),
        ("Sisin Sakladıkları 2: Ortak Ruh", "Miyase Sertbarut", "Tudem", 152),
        ("Pal Sokağı Çocukları", "Ferenc Molnár", "Yapı Kredi Yayınları", 235),
    ],
}

# Şube özel listesi varsa seviye listesinin yerine geçer.
OKUMA_KITAPLARI_SINIF: dict[str, list[tuple[str, str, str, int]]] = {
    "5/A": [
        ("Kiki ve Bir Diğer Cadı", "Eiko Kadono", "Can Çocuk Yayınları", 260),
        ("Abartma Tozu", "Şermin Yaşar", "Taze Kitap", 160),
        ("Şamatalı Köy", "Astrid Lindgren", "Pegasus Çocuk Yayınları", 104),
        ("Martıya Uçmayı Öğreten Kedi", "Luis Sepúlveda", "Can Çocuk Yayınları", 128),
        ("Yerdeniz Büyücüsü", "Ursula K. Le Guin", "Metis Yayınları", 188),
        ("Gece Gündüzüm Olsa", "Andreas Steinhöfel", "Günışığı Kitaplığı", 68),
        ("Gemideki Cesur Ses", "İdil Pişgin", "Tudem", 109),
        ("Yeryüzünün Kalbi", "Özgür Balpınar", "Timaş Genç", 216),
        ("Kiraz Ağacıyla Aramızdaki Mesafe", "Paola Peretti", "Timaş Genç", 208),
        ("Yıldızlara Yakın", "Metin Özdamarlar", "Eğlenceli Bilgi", 144),
        ("Zerdali Dedemle Bir Yıl", "Yaşar Bayraktar", "Timaş İlk Genç", 144),
        ("Yürüyen Şato", "Diana Wynne Jones", "Domingo Yayınevi", 356),
        ("Eşek Klanı", "Bilgin Adalı", "Can Çocuk Yayınları", 83),
        ("Savaşı Bitiren Sinek", "Bryndís Björgvinsdóttir", "Can Yayınları", 108),
        ("Dünya Sular Altında", "Cary Fagan", "Günışığı Kitaplığı", 111),
        ("Dedemin Bakkalı", "Şermin Yaşar", "Taze Kitap", 200),
        ("Şamatalı Köy'de Eğlence", "Astrid Lindgren", "Pegasus Çocuk Yayınları", 126),
        ("Dilek Kütüphanesi", "Christine Evans", "Tudem", 87),
        ("Kiralık Canavar", "Andreas Steinhöfel", "Günışığı Kitaplığı", 101),
        ("Yabanın Çağrısı", "Jack London", "Can Çocuk Yayınları", 124),
        ("Bisiklet Yarışçıları", "Ferda İzbudak Akıncı", "Tudem", 159),
        ("Zaman Bisikleti", "Bilgin Adalı", "Can Çocuk Yayınları", 128),
        ("Dünyanın En Önemli Öğrencisi", "Şermin Yaşar", "Taze Kitap", 157),
    ],
}
