"""
Erenler Cumhuriyet Ortaokulu — Günlük Bilgi Yarışması Soru Bankası
Format: (soru_metni, secenek_A, secenek_B, secenek_C, secenek_D, dogru)
dogru: 'A' | 'B' | 'C' | 'D'
Her sınıf × her ders için 35 soru = 840 toplam soru
"""

SORULAR: dict[int, dict[str, list[tuple]]] = {

# ══════════════════════════════════════════════════════════════════════
# 5. SINIF
# ══════════════════════════════════════════════════════════════════════
5: {

"Türkçe": [
("İki cümleyi birbirine bağlayan sözcüklere ne denir?","Zamir","Bağlaç","Edat","Ünlem","B"),
("'Damlaya damlaya göl olur' sözü nasıl bir ifadedir?","Deyim","Atasözü","Bilmece","Masal","B"),
("Aşağıdakilerden hangisi isim değildir?","Kitap","Güzel","Masa","Kalem","B"),
("Şiirde satır sonlarındaki ses benzerliğine ne denir?","Ölçü","Redif","Uyak","Aliterasyon","C"),
("'Ali okula gider.' cümlesinde özne hangisidir?","okula","gider","Ali","okula gider","C"),
("Zıt anlamlı çift hangisidir?","Hızlı-Çabuk","Büyük-Küçük","İyi-İyi","Araba-Oto","B"),
("Türk alfabesinde kaç harf vardır?","26","28","29","31","C"),
("'Benzetme' için kullanılan edebi sanata ne denir?","Kişileştirme","Teşbih","Abartma","Karşıtlık","B"),
("Fiil ne anlatan sözcüktür?","Ad anlatan","Durum ya da hareket anlatan","Sıfat anlatan","Sayı anlatan","B"),
("Masal türü için hangisi doğrudur?","Gerçek hayatı anlatır","Olağanüstü olaylar içerir","Her zaman şiir biçimindedir","Gerçek kişileri anlatır","B"),
("Sözcüklerin çoğul eki aşağıdakilerden hangisidir?","-lı/-li","-lar/-ler","-da/-de","-la/-le","B"),
("'Gözleri dört açmak' deyiminin anlamı nedir?","Dört gözle bakmak","Çok dikkatli olmak","Kör olmak","Çok uyumak","B"),
("Eş anlamlı çift hangisidir?","Güzel-Çirkin","Araba-Otomobil","Büyük-Küçük","İyi-Kötü","B"),
("Bir metinde ana düşünce nerede yer alabilir?","Sadece başta","Sadece sonda","Başta, ortada veya sonda","Sadece başlıkta","C"),
("Türkçede sesli harf sayısı kaçtır?","4","6","8","10","C"),
("Noktalı virgül (;) hangi durumda kullanılır?","Cümle sonunda","Sıralanmış birden çok öge arasında","Soru cümlesi sonunda","Ünlem cümlesi sonunda","B"),
("Kişileştirme sanatı için hangisi doğru bir örnektir?","Dağ gibi adam","Güneş gülümsedi","Kar gibi beyaz","Deli gibi koştu","B"),
("Türkçede büyük harfle başlayan nedir?","Genel isimler","Sadece cümle başı","Özel isimler ve cümle başları","Eylemler","C"),
("Hikaye türünün özelliği nedir?","Uzundur, birçok bölüm içerir","Kısa, az kişiyle sınırlı olay anlatır","Sahnede oynanır","Her zaman şiir biçimindedir","B"),
("Aşağıdakilerden hangisi soru cümlesidir?","Çok yoruldum.","Ne kadar da güzel!","Nereye gidiyorsun?","Hemen eve git.","C"),
("'Kitap kurdu' deyiminin anlamı nedir?","Kitapları yiyen böcek","Çok kitap okuyan kişi","Eski kitap","Kitap kaplığı böcek","B"),
("Paragraf nedir?","Birden fazla cümleden oluşan düşünce bütünüdür","Tek cümleden oluşan yazıdır","Şiirin bir bölümüdür","Mektup türüdür","A"),
("Sesiz harfler kaç tanedir?","15","17","19","21","D"),
("Abartma sanatı için hangisi örnektir?","Gözleri yıldız gibi","Kalbi taş gibi","Dünyaları verse almam","Güneş gülümsedi","C"),
("Mektup yazarken önce ne yazılır?","İmza","Selamlama","Tarih ve yer","Konu başlığı","C"),
("Öznel cümle ne demektir?","Kanıtlanabilir cümle","Kişiden kişiye değişen yargı içeren cümle","Tarih bildiren cümle","Soru cümlesi","B"),
("Roman türü hikayeden farkı nedir?","Daha kısa ve az kişiseldir","Daha uzun ve geniş olay örgüsüne sahiptir","Konusu gerçek hayat değildir","Şiir biçiminde yazılır","B"),
("Bağlaç örneği hangisidir?","güzel","ve","ama-fakat","kitap","B"),
("Sıfat ne anlatan sözcüktür?","İsim anlatan","İsmi niteleyen veya belirten","Hareket anlatan","Durum anlatan","B"),
("Türkçe ders kitabında 'yazım kuralları' bölümü neyi öğretir?","Okuma hızını","Kelimelerin doğru yazılışını","Şiir yazmayı","Konuşmayı","B"),
("Aşağıdaki cümlelerin hangisinde ünlem işareti doğru kullanılmıştır?","Ne kadar güzel!","Ali geldi!","Kitabımı aldım!","Okula gidiyorum!","A"),
("Tablo ve grafikler Türkçe dersinde ne için incelenir?","Matematiği öğrenmek için","Bilgi okuma ve yorumlama becerisi için","Resim çizimi için","Şiir analizi için","B"),
("Yapısına göre yalnızca bir kökten oluşan sözcüğe ne denir?","Türemiş sözcük","Basit sözcük","Bileşik sözcük","Öbek","B"),
("Türkçede soru eki hangisidir?","-mı/-mi/-mu/-mü","-lı/-li","-lar/-ler","-da/-de","A"),
("Anlatım bozukluğu nedir?","Çok uzun cümle kurmak","Anlama zarar veren yanlış ifade","Çok kısa cümle kurmak","Sadece yabancı kelime kullanmak","B"),
],

"Matematik": [
("1 000 000'a (bir milyon) en yakın sayı hangisidir?","999 999","999 998","1 000 001","999 000","A"),
("720 ÷ 8 = ?","80","90","85","95","B"),
("Bir dikdörtgenin uzun kenarı 12 cm, kısa kenarı 7 cm ise çevresi kaç cm'dir?","38","84","19","42","A"),
("1/2 + 1/4 = ?","2/6","3/4","1/2","2/4","B"),
("Aşağıdaki sayılardan hangisi 3'e tam bölünür?","125","247","333","148","C"),
("Bir üçgenin iç açıları toplamı kaç derecedir?","90°","180°","270°","360°","B"),
("456 × 5 = ?","2230","2280","2180","2080","B"),
("0,5 ondalık sayısı kesir olarak nedir?","1/4","5/10","1/2","her ikisi B ve C doğru","C"),
("Bir kutuda 24 elma var. Bu elmaların 1/3'ü kaç elmadır?","6","8","10","12","B"),
("500 - 237 = ?","273","263","283","253","B"),
("Kare ne demektir?","Dört eşit kenarlı, tüm açıları 90° olan şekil","Sadece iki eşit kenarlı şekil","Üç kenarlı şekil","Beş kenarlı şekil","A"),
("3², yani 3 üssü 2 kaçtır?","6","9","8","27","B"),
("1 km kaç metredir?","100 m","500 m","1000 m","10 000 m","C"),
("Bir sayının %10'u 5 ise bu sayı kaçtır?","50","25","15","10","A"),
("Kesirlerden hangisi en büyüktür?","1/3","1/2","1/4","1/5","B"),
("56 + 38 + 44 = ?","138","136","140","132","A"),
("12 × 12 = ?","124","144","134","142","B"),
("Çevresi 36 cm olan bir karenin kenar uzunluğu kaçtır?","8 cm","6 cm","9 cm","12 cm","C"),
("1 saat kaç dakikadır?","50","70","60","90","C"),
("Hangisi tek sayıdır?","12","24","31","50","C"),
("3/5 + 1/5 = ?","4/5","4/10","2/5","3/10","A"),
("Bir üçgende iki açı sırasıyla 60° ve 80° ise üçüncü açı kaçtır?","40°","30°","50°","60°","A"),
("1 000'den küçük en büyük 3 basamaklı sayı hangisidir?","999","990","998","909","A"),
("Bir paralel kenarın taban uzunluğu 10 cm, yüksekliği 6 cm ise alanı kaçtır?","60 cm²","32 cm²","16 cm²","56 cm²","A"),
("Hangi ifade doğrudur?","5 > 7","3 < 1","9 > 6","4 > 10","C"),
("2/3 × 3 = ?","6/3","2","2/9","6","B"),
("Bir romanda sayfa numaraları 1'den 200'e kadar gidiyorsa toplam kaç rakam kullanılmıştır?","492","400","200","350","A"),
("En küçük asal sayı hangisidir?","0","1","2","3","C"),
("Bir dairenin yarıçapı 7 cm ise çapı kaçtır?","7 cm","14 cm","21 cm","49 cm","B"),
("456 sayısının basamak değerleri doğru verilmiştir: 400 + 50 + 6 — Bu doğru mu?","Hayır, 400+56 olmalı","Hayır, 46+50 olmalı","Evet, doğrudur","Hayır, 500+50+6","C"),
("1/2 ÷ 2 = ?","1/4","1","2","1/6","A"),
("Bir üçgenin üç kenarı 5, 5 ve 8 cm ise bu nasıl bir üçgendir?","Eşkenar","İkizkenar","Çeşitkenar","Dik","B"),
("Hangi sayı 6'nın katıdır?","14","25","36","43","C"),
("Ondalık sayılardan hangisi en küçüktür?","0,9","0,09","0,9","0,099","D"),
("3 saat 45 dakika kaç dakikadır?","225 dk","180 dk","210 dk","205 dk","A"),
],

"Fen Bilimleri": [
("Işık hangi hızla yayılır?","Ses hızında","Sonsuz hızda","Yaklaşık 300.000 km/s","Yaklaşık 300 km/s","C"),
("Katı cisimler ne zaman çözünür?","Soğuk suda daha iyi çözünür","Sıcak suda daha iyi çözünür","Sıcaklığın etkisi yoktur","Sadece gazlarda çözünür","B"),
("Bitkiler fotosentez ile ne üretir?","Besin (şeker) ve oksijen","Karbondioksit ve su","Azot ve hidrojen","Mineral ve tuz","A"),
("Insan vücudundaki en uzun kemik hangisidir?","Omurga","Kafatası","Uyluk kemiği","Kaburga","C"),
("Ses boşlukta ilerleyebilir mi?","Evet, çok hızlı","Evet, ama yavaş","Hayır, ilerleyemez","Evet, su kadar hızlı","C"),
("Aşağıdaki maddelerden hangisi karışım değildir?","Tuzlu su","Hava","Altın","Çay","C"),
("Mıknatıs hangi maddeleri çeker?","Tüm metaller","Demir, kobalt, nikel","Plastik ve ahşap","Sadece demir","B"),
("Işığın bir yüzeyden geri dönmesine ne denir?","Kırılma","Yansıma","Emilme","Saçılma","B"),
("Bitkilerde su ve mineraller yapraklara nasıl taşınır?","Soymuk boruyla","Odun boruyla","Kılcal borularla","Doğrudan kökten","B"),
("Ekosistem nedir?","Yalnızca canlıların oluşturduğu sistem","Canlı ve cansız varlıkların bir arada oluşturduğu sistem","Yalnızca bitkiler","Yalnızca hayvanlar","B"),
("Ay neden kendi ışığı yoktur?","Çok küçük olduğu için","Güneşten çok uzak olduğu için","Işık yayamaz, güneş ışığını yansıtır","Bulutların arkasında olduğu için","C"),
("Isı enerjisi ölçmek için hangi alet kullanılır?","Termometre","Barometre","Dinamometre","Ampermetre","A"),
("Solunum sistemi organlarının doğru sıralaması hangisidir?","Akciğer-Bronş-Gırtlak-Burun","Burun-Gırtlak-Soluk borusu-Bronş-Akciğer","Akciğer-Kalp-Burun","Mide-Barsak-Akciğer","B"),
("Geri dönüşüm yapılabilecek madde hangisidir?","Karton","Plastik","Cam","Hepsi","D"),
("Kaldıraçlar hangi ilkeyle çalışır?","Isı","Ses","Denge ve kuvvet","Işık","C"),
("Canlıları inceleyen bilim dalı hangisidir?","Kimya","Fizik","Biyoloji","Astronomi","C"),
("Su hangi sıcaklıkta kaynar? (deniz seviyesinde)","50°C","80°C","100°C","120°C","C"),
("Karbondioksit hangi durumlarda oluşur?","Solunum ve yanma sırasında","Sadece yanma sırasında","Sadece fotosentezde","Solunum ve fotosentezde","A"),
("Güneş sistemi gezegenleri sayısı kaçtır?","7","8","9","10","B"),
("Isı iletimi bakımından metaller nasıldır?","İyi ısı iletkenidir","Kötü ısı iletkenidir","Isıyı geçirmez","Isı iletimi yoktur","A"),
("Besin zinciri nedir?","Yalnızca otçulları anlatan zincir","Canlılar arasındaki beslenme ilişkisini gösteren zincir","Tarım ürünleri zinciri","Ekosistemsiz zincir","B"),
("Yoğunluk formülü nedir?","D = V × m","D = m / V","D = m + V","D = V / m","B"),
("Yerçekimi kuvveti nedir?","Dünya'nın cisimleri içine çekme kuvveti","Cisimlerin birbirini itmesi","Manyetik kuvvet","Rüzgar kuvveti","A"),
("Maddenin katıdan sıvıya geçişine ne denir?","Donma","Erime","Buharlaşma","Yoğuşma","B"),
("Bağışıklık sistemi neden önemlidir?","Sindirime yardım eder","Vücudu hastalıklara karşı korur","Oksijen taşır","Besin üretir","B"),
("Çiçekli bitkide tohum nerede oluşur?","Çiçeğin taç yapraklarında","Meyvenin içinde","Gövdede","Kökde","B"),
("Atom nedir?","Maddenin en küçük yapı taşıdır","Maddenin en büyük parçasıdır","Yalnızca katılarda bulunur","Yalnızca gözle görülebilir","A"),
("Sürtünme kuvveti ne zaman ortaya çıkar?","İki yüzey hareket ettiğinde","Yalnızca havada","Yalnızca suda","Isıtma sırasında","A"),
("Hangi madde elektriği iletir?","Ahşap","Plastik","Bakır tel","Kağıt","C"),
("Hücre zarının görevi nedir?","Fotosentez yapmak","Hücreye şekil vermek ve madde geçişini düzenlemek","Enerji üretmek","Protein sentezlemek","B"),
("Güneş tutulması neden olur?","Ay, Dünya ile Güneş arasına girince","Dünya, Ay ile Güneş arasına girince","Güneş'in sönmesi","Yıldızların toplanması","A"),
("Canlıların sınıflandırılmasında en küçük grup hangisidir?","Alem","Cins","Tür","Sınıf","C"),
("Deney yapılırken değişmeyen koşullara ne denir?","Bağımlı değişken","Bağımsız değişken","Sabit değişken","Kontrol grubu","C"),
("Asitler turnusol kağıdını hangi renge boyar?","Maviye","Kırmızıya","Sarıya","Yeşile","B"),
("Hangi organ kanı pompalayarak vücuda gönderir?","Akciğer","Beyin","Kalp","Böbrek","C"),
],

"Sosyal Bilgiler": [
("Türkiye kaç coğrafi bölgeye ayrılmaktadır?","5","7","8","6","B"),
("Ülkemizin başkenti hangisidir?","İstanbul","İzmir","Ankara","Bursa","C"),
("Türkiye hangi kıtada yer alır?","Asya","Avrupa","Asya ve Avrupa","Afrika","C"),
("Anadolu'daki ilk uygarlıklardan biri olan Hititlerin başkenti neresidir?","Gordion","Hattuşa","Alacahöyük","Çatalhöyük","B"),
("Haritada kuzey yönü genellikle hangi yöndedir?","Sağ","Sol","Aşağı","Yukarı","D"),
("Türkiye'nin en uzun nehri hangisidir?","Fırat","Kızılırmak","Nil","Sakarya","B"),
("Demokrasi kavramı hangi antik medeniyete aittir?","Roma","Mısır","Yunan","Pers","C"),
("Türkiye Cumhuriyeti ne zaman kurulmuştur?","1920","1921","1923","1922","C"),
("İpek Yolu neden önemlidir?","Deniz yolu bağlantısıdır","Doğu-Batı ticaret yoluydu","Yalnızca askeri yoldu","Osmanlı'ya özeldi","B"),
("Nüfus yoğunluğu ne demektir?","Ülkedeki toplam nüfus","Birim alandaki insan sayısı","Büyük şehir nüfusu","Göç edenlerin sayısı","B"),
("Mezopotamya uygarlıkları hangi iki nehir arasında kurulmuştur?","Nil - Fırat","Fırat - Dicle","İndus - Ganj","Sarı Irmak - Yangtze","B"),
("Türkiye'nin en kalabalık ili hangisidir?","Ankara","İzmir","İstanbul","Bursa","C"),
("Haritada ölçek nedir?","Renk kodlaması","Haritanın gerçek mesafeye oranı","Yükseklik göstergesi","Yön oku","B"),
("Karadeniz kıyılarının genel iklim özelliği nedir?","Kurak ve sıcak","Yazları kurak, kışları yağışlı","Yıl boyu yağışlı","Yıl boyu kurak","C"),
("Türkiye'nin en yüksek dağı hangisidir?","Erciyes","Uludağ","Ağrı Dağı","Süphan","C"),
("Tarihte ilk yazıyı hangi medeniyet icat etmiştir?","Mısırlılar","Sümerler","Hititler","Romalılar","B"),
("Vatandaşlık hakkı nedir?","Yalnızca oy kullanma hakkı","Bir ülke vatandaşlarına tanınan hakların bütünü","Yalnızca çalışma hakkı","Yalnızca eğitim hakkı","B"),
("Göç neden olur?","Yalnızca savaş nedeniyle","Ekonomik, sosyal, doğal felaket gibi çeşitli nedenlerle","Yalnızca iklim nedeniyle","Yalnızca deprem nedeniyle","B"),
("Türkiye'de tarım en çok hangi bölgede yapılmaktadır?","Ege","İç Anadolu","Karadeniz","Akdeniz ve İç Anadolu başta olmak üzere farklı bölgelerde","D"),
("Atatürk'ün soyadı hangi kanunla verilmiştir?","Soyadı Kanunu (1934)","Medeni Kanun","Millet Mektepleri Kanunu","Harf Devrimi Kanunu","A"),
("Orta Anadolu'nun genel arazi yapısı nasıldır?","Dağlık ve ormanlık","Düz ve bozkır","Sulak ve verimli","Çöl ve kum","B"),
("Ülkemizde ilköğretim kaç yıldır?","6","7","8","9","C"),
("Türkiye'nin en önemli tahıl ürünü hangisidir?","Mısır","Buğday","Çeltik","Arpa","B"),
("'Siyasi harita' neyi gösterir?","Dağ ve nehirleri","Ülke sınırlarını ve şehirleri","Arazi yüksekliklerini","Orman alanlarını","B"),
("Orta Anadolu'da ekim biçerler ne zaman kullanılır?","Kışın","Yazın","İlkbaharda","Sonbaharda","B"),
("Türkiye'de hangi enerji kaynağı en çok kullanılır?","Güneş","Nükleer","Doğalgaz ve termik","Dalga enerjisi","C"),
("Ege bölgesinin önemli tarım ürünü hangisidir?","Çay","İncir ve zeytin","Buğday","Şeker pancarı","B"),
("Türkiye Büyük Millet Meclisi kaç milletvekilinden oluşur?","400","550","600","500","C"),
("Küresel ısınma nedir?","Dünya'nın soğuması","Atmosferdeki sera gazı artışı nedeniyle Dünya'nın ısınması","Güneş'in ısı kaybetmesi","Kutupların erimesi","B"),
("Karadeniz bölgesinde en çok yetiştirilen tarım ürünü nedir?","Pamuk","Çay ve fındık","Üzüm","Buğday","B"),
("Tarihte para kullanılmadan önce ne yapılırdı?","Vergi verilirdi","Trampa (değiş tokuş) yapılırdı","Altın kullanılırdı","Borç alınırdı","B"),
("Türkiye'de kurulan ilk devlet hangisidir?","Osmanlı","Selçuklu","Türkiye Cumhuriyeti","Göktürk","D"),
("İnsan haklarının temel belgesi hangisidir?","Türk Anayasası","BM İnsan Hakları Evrensel Bildirisi","Lozan Antlaşması","Sevr Antlaşması","B"),
("Türk Bayrağı'ndaki hilal ve yıldızın rengi nedir?","Beyaz","Sarı","Kırmızı","Altın sarısı","A"),
("Türkiye'nin komşuları arasında hangisi yer almaz?","Yunanistan","Irak","Mısır","Suriye","C"),
],

"İngilizce": [
("What is the English word for 'kedi'?","dog","cat","bird","fish","B"),
("Which sentence is correct?","I am a student.","I are a student.","I is a student.","Me am student.","A"),
("What is the plural of 'child'?","childs","childes","children","childre","C"),
("'Mavi' in English is?","green","blue","red","yellow","B"),
("How do you say 'Kaç yaşındasın?'?","How old are you?","How are you?","What is your name?","Where are you from?","A"),
("Which is a day of the week?","January","Monday","Summer","April","B"),
("'She ___ a teacher.' Fill in the blank.","am","are","is","be","C"),
("What does 'hungry' mean?","aç","yorgun","mutlu","üzgün","A"),
("Which number comes after 'nine'?","eleven","eight","ten","twelve","C"),
("'Good morning' is said at what time?","Evening","Night","Morning","Afternoon","C"),
("What is the opposite of 'hot'?","big","cold","tall","slow","B"),
("'I ___ to school every day.' (go/goes/went)","goes","went","go","going","C"),
("Which animal can fly?","dog","cat","bird","fish","C"),
("What does 'book' mean?","kalem","silgi","kitap","defter","C"),
("'They ___ playing football now.' (is/are/am)","is","am","are","be","C"),
("What color is the sun?","blue","green","yellow","purple","C"),
("How many months are in a year?","10","11","12","13","C"),
("'My name ___ Ali.'","am","are","is","be","C"),
("Which is a fruit?","carrot","potato","apple","onion","C"),
("What does 'fast' mean?","yavaş","hızlı","büyük","küçük","B"),
("'___ you speak English?' (Do/Does/Are)","Does","Are","Do","Is","C"),
("Which is a body part?","chair","table","arm","window","C"),
("What does 'every day' mean?","bazen","her zaman","her gün","hiçbir zaman","C"),
("'She has ___ brothers.' (two/twice/twos)","twice","twos","two","twices","C"),
("Which is a school subject?","bedroom","kitchen","maths","garden","C"),
("'Where ___ you from?' (are/is/am)","is","am","are","be","C"),
("What does 'happy' mean?","mutlu","üzgün","sinirli","korkmuş","A"),
("How do you say 'Teşekkür ederim'?","Sorry","Excuse me","Thank you","Please","C"),
("'I like ___ football.' (play/playing/played)","play","played","plays","playing","D"),
("What is the English for 'elma'?","pear","banana","orange","apple","D"),
("Which season comes after winter?","autumn","summer","spring","fall","C"),
("'He ___ to bed at 9 o'clock.' (go/goes/going)","going","go","gone","goes","D"),
("What does 'tall' mean?","kısa","uzun boylu","şişman","zayıf","B"),
("'I have ___ cat.' (a/an/the)","an","the","a","–","C"),
("Which is a color?","square","triangle","purple","circle","C"),
],

"Din Kültürü": [
("İslam'ın iki temel kaynağı nedir?","Kur'an ve Sünnet","Tevrat ve İncil","Kur'an ve İncil","Sünnet ve Tevrat","A"),
("Kuran-ı Kerim kaç sureden oluşur?","99","100","114","112","C"),
("İslam'ın beş şartından biri olan 'oruç' hangi ayda tutulur?","Şevval","Şaban","Ramazan","Muharrem","C"),
("Namaz kaç vakittir?","3","4","5","6","C"),
("Hz. Muhammed'in doğduğu şehir neresidir?","Medine","Mekke","Taif","Kûfe","B"),
("'Allah birdir' ilkesi Tevhid'in ne anlama gelir?","Allah'ın üç olması","Allah'ın bir ve eşsiz olması","Allah'ın görünür olması","Allah'ın kızgın olması","B"),
("Kabe hangi şehirdedir?","Medine","Taif","Mekke","Kudüs","C"),
("Hac ibadeti hangi ayda yapılır?","Ramazan","Şevval","Zilhicce","Muharrem","C"),
("Hz. Peygamber'in sözlerine ne denir?","Ayet","Hadis","Sure","Dua","B"),
("Zekât kime verilir?","Zengine","Muhtaç ve fakir olanlara","Devlete","Camiiye","B"),
("Kur'an'ın ilk suresi hangisidir?","Bakara","İhlas","Fatiha","Nâs","C"),
("İslam'ın getirdiği ahlaki değerlerden biri hangisi değildir?","Dürüstlük","Yardımseverlik","Kibir","Sabır","C"),
("Meleklerin özellikleri arasında hangisi doğrudur?","Erkek veya dişidir","Yiyip içerler","Günah işlemezler","Görünür olurlar","C"),
("Hz. İbrahim kimdir?","Bir peygamberdir","Bir halifedir","Bir komutandır","Bir padişahtır","A"),
("'Bismillahirrahmanirrahim' ne anlama gelir?","Allah'a hamdolsun","Rahman ve Rahim olan Allah'ın adıyla","Allah'tan başka ilah yoktur","Allah büyüktür","B"),
("İslam'da beş vakit namazın isimleri doğru sıralanan hangisidir?","Sabah, öğle, ikindi, akşam, yatsı","Sabah, öğle, ikindi, akşam, gece","Fecr, öğle, ikindi, güneş, akşam","Sabah, öğlen, cuma, akşam, yatsı","A"),
("Kur'an'daki ayetlerin toplandığı bölümlere ne denir?","Cüz","Bölüm","Sure","Paragraf","C"),
("İslam'da yasaklanan yiyeceklerden biri hangisidir?","Et","Meyve","Domuz eti","Balık","C"),
("Hz. Âdem'e göre ilk peygamber kimdir?","Hz. Nuh","Hz. İbrahim","Hz. Âdem","Hz. Musa","C"),
("Kur'an Arapça'da ne anlama gelir?","Okunmuş","Okunan, tilâvet edilen","Yazılan","Öğretilen","B"),
("Oruç tutmak hangi pilara girer?","Namaz","İslam'ın 3. şartı olan oruç","Hac","Zekât","B"),
("Sabah namazı kaç rekâttır?","2","3","4","5","A"),
("'Tevekkül' ne demektir?","Allah'tan korkmak","Allah'a güvenerek sebebe sarılmak","Namaz kılmak","Oruç tutmak","B"),
("Peygamberlerin özelliklerinden hangisi doğrudur?","Yanılabilirler","Masumdur (günahsız)","Ölümlü değillerdir","Sıradan insanlardır","B"),
("Hz. Musa'ya indirilen kutsal kitap hangisidir?","İncil","Zebur","Tevrat","Kur'an","C"),
("'Sadaka' nedir?","Zorunlu vergi","Gönüllü yardım","Cami bağışı","Farz olan yardım","B"),
("İslam'da büluğa erme ne zaman gerçekleşir?","10 yaşında","Reşit olunca","Ergenlik dönemiyle birlikte","20 yaşında","C"),
("Kıble yönü nereye doğrudur?","Medine'ye","Kudüs'e","Mekke'ye (Kabe'ye)","Doğuya","C"),
("Hz. Peygamber Mekke'den Medine'ye ne zaman hicret etmiştir?","610","622","630","632","B"),
("Cumartesi günü namaz kılmak farz mıdır?","Evet, haftada bir","Hayır, her gün 5 vakit kılınır","Sadece cuma","Sadece bayramlarda","B"),
("İslam'da dürüstlük ilkesi için kullanılan Arapça kelime nedir?","Sadakat","Sıdk","Adalet","İhsan","B"),
("Tekbir ne demektir?","Namaz kılmak","'Allah-u Ekber' demek","Oruç tutmak","Zekat vermek","B"),
("Kur'an'ın son suresi hangisidir?","Fatiha","Bakara","Felak","Nâs","D"),
("'Ahlak' kavramı ne anlama gelir?","Fiziksel güzellik","İyi huy ve davranış biçimleri","Dini ritüeller","Giyim kuşam","B"),
("Hz. İsa'ya indirilen kitap hangisidir?","Tevrat","Zebur","İncil","Kur'an","C"),
],

}, # end of grade 5

# ══════════════════════════════════════════════════════════════════════
# 6. SINIF
# ══════════════════════════════════════════════════════════════════════
6: {

"Türkçe": [
("Bir metnin anlatım türleri arasında 'betimleme' ne demektir?","Bir konuyu tartışmak","Bir varlığı ya da yeri ayrıntılı anlatmak","Olay sırasını vermek","Kişileri konuşturmak","B"),
("Şiirde dizelerin hece sayısına göre düzenlenmesine ne denir?","Uyak","Kafiye","Hece ölçüsü","Redif","C"),
("Anlatı metninde 'olay örgüsü' nedir?","Metindeki kişiler","Olayların biri birini izleyen dizisi","Zaman ve mekân","Tema","B"),
("'Öznel yargı' nasıl tanımlanır?","Herkese göre aynı olan yargı","Kişiden kişiye değişen yargı","Kanıtlanabilen yargı","Kesin bilgi içeren yargı","B"),
("Aşağıdakilerden hangisi bağlaç değildir?","fakat","ama","oysa","güzel","D"),
("Deyimler gerçek anlamıyla mı kullanılır?","Evet, gerçek anlamıyla","Hayır, mecaz anlamıyla","Bazen gerçek bazen mecaz","Yalnızca şiirlerde","B"),
("Yazım kuralına göre 'de' ayrı yazıldığında ne işlevi vardır?","Bağlaç","Ek olarak bulunma hâli","Zamir","Fiil","A"),
("'Gözden düşmek' deyiminin anlamı nedir?","Görüş kaybetmek","İtibarını yitirmek","Yüksekten düşmek","Çok yorulmak","B"),
("Nesnel cümle hangi özelliği taşır?","Kişisel yargı içerir","Kanıtlanabilir","Duygusal ifade içerir","Belirsizlik içerir","B"),
("Sıfat tamlamasında sıfat ne yapar?","Eylemi niteler","İsmi niteler","Zamirin yerini tutar","Bağlayıcı görev üstlenir","B"),
("'Paragraf' için hangisi doğrudur?","Her zaman bir cümleden oluşur","Bir düşünce birimini oluşturan cümle grubudur","Yalnızca anlatı metinlerinde bulunur","Bölüm başlığıdır","B"),
("Hangi sözcük türü cümle içinde ismin yerini tutar?","Sıfat","Fiil","Zamir","Bağlaç","C"),
("Yazım kuralına göre büyük harf kullanılmayan yer hangisidir?","Cümle başı","Özel isimler","Genel adlar","Ülke adları","C"),
("Anlatı metninde 'tema' nedir?","Olayların geçtiği yer","Metnin temel düşünce ya da duygusu","Anlatıcının adı","Kişi sayısı","B"),
("'Sıra cümle' nedir?","Birbirine bağlanmayan iki cümle","Virgülle sıralanan birden çok cümle","Soru cümlesi","Ünlem içeren cümle","B"),
("Sözcüğün köküne getirilen ve yeni anlam katan eklere ne denir?","Çekim eki","Yapım eki","Bağlaç eki","Zamir eki","B"),
("'Adıl' sözcüğü neyin karşılığıdır?","Sıfat","Bağlaç","Zamir","Edat","C"),
("Aşağıdakilerden hangisi çok anlamlı sözcüğe örnek değildir?","Baş","Kanat","Kalem","Kol","C"),
("Haber cümlesi nedir?","Soru içeren cümle","Emir bildiren cümle","Olayı ya da durumu bildiren cümle","Dilek bildiren cümle","C"),
("Türkçede ünlü uyumu kuralı nedir?","Ünsüzlerin uyumu","Sözcükteki ünlülerin belirli bir uyum içinde olması","İki sözcüğün uyumu","Yabancı kelimelerin uyumu","B"),
("Anlatı metninde çatışma nedir?","Kahramanın adı","Kahramanlar arasındaki sorun ya da gerilim","Olayın çözümü","Mekânın özelliği","B"),
("Türkçe kökenli olmayan sözcüğe ne denir?","Kök sözcük","Alıntı sözcük","Türemiş sözcük","Bileşik sözcük","B"),
("'Mecaz anlam' nedir?","Sözcüğün sözlük anlamı","Sözcüğün temel anlamından uzaklaşmış anlamı","Sözcüğün çoğul anlamı","Sözcüğün zıt anlamı","B"),
("Yazılı anlatımda paragrafın ilk satırı nasıl yazılır?","Sola dayalı","İçe girintili","Büyük harfle","Kalın harfle","B"),
("Şiirde 'bent' ne demektir?","Şiirin bütünü","Şiirde birden fazla dizeyi kapsayan bölüm","Şiirin son satırı","Uyak","B"),
("'Eylem' sözcüğü neyle aynı anlamdadır?","İsim","Fiil","Sıfat","Zarf","B"),
("Türkçede fiil çekiminde 'zaman' eki neyi gösterir?","Kişiyi","Olayın ne zaman gerçekleştiğini","Sayıyı","Belirtili ismi","B"),
("'Bildirme kipi' hangileridir?","Dilek kipleri","Şimdiki, geçmiş, geniş, gelecek zaman","Şart ve istek","Emir ve gereklilik","B"),
("Tiyatro metninin temel özelliği nedir?","Şiir biçiminde yazılır","Sahnede oynanmak için yazılır","Roman kadar uzundur","Kişisizdir","B"),
("'Karşıt anlam' için doğru çift hangisidir?","Gelmek-Varmak","Koşmak-Yürümek","Açmak-Kapamak","Gülmek-Eğlenmek","C"),
("Sıfat-fiil nedir?","Hem sıfat hem fiil özelliği taşıyan sözcük","Yalnızca sıfat olan sözcük","Yalnızca fiil olan sözcük","Fiilden türememiş sözcük","A"),
("'Güzel Türkçe' derken kast edilen nedir?","Yabancı sözcük kullanmak","Sade, anlaşılır, öz Türkçe kullanmak","Çok süslü anlatım","Çok uzun cümle kurmak","B"),
("Dilin işlevleri arasında hangisi yoktur?","Anlatım","İletişim","Eğitim","Uyku","D"),
("'Söylem' nedir?","Sözlü ya da yazılı ifade biçimi","Yalnızca şiirde kullanılan","Yalnızca konuşma dili","Gizli dil","A"),
("Türkçede 'ses olayları'na örnek aşağıdakilerden hangisidir?","Ünlü düşmesi","Bağlaç çıkması","Soru eki","Çoğul eki","A"),
],

"Matematik": [
("Bir tam sayının mutlak değeri nedir?","Kendisi","Sayının işaret görmeksizin büyüklüğü","Sayının negatifi","Sayının karesi","B"),
("(-5) + (-3) = ?","8","-8","2","-2","B"),
("3/4 ÷ 1/2 = ?","3/8","3/2","6/4","1/6","B"),
("(-4) × (-6) = ?","-24","24","-10","10","B"),
("Bir üçgenin alanı formülü nedir?","Taban × Yükseklik","(Taban × Yükseklik) / 2","Taban + Yükseklik","2 × (Taban + Yükseklik)","B"),
("1/3 + 2/5 = ?","3/8","11/15","3/15","2/8","B"),
("(-12) ÷ 4 = ?","3","-3","8","-8","B"),
("6² - 4² = ?","20","32","4","52","A"),
("Bir paralelkenarın alanı nasıl hesaplanır?","Taban × Yükseklik","2 × (Taban + Yan Kenar)","Taban × Yan Kenar","(Taban × Yükseklik) / 2","A"),
("Oranlarda a/b = c/d ise ne söylenebilir?","a × b = c × d","a × d = b × c","a + b = c + d","a - b = c - d","B"),
("0,375'i kesire çevirin.","3/8","375/1000 sadeleşirse 3/8","Her ikisi doğru","Sadece B","C"),
("%-25 indirim yapılırsa 200 TL'lik ürün kaç TL olur?","175 TL","150 TL","160 TL","180 TL","B"),
("(-2)³ = ?","-8","8","-6","6","A"),
("Bir yamuk alan formülü nedir?","(a+b)/2 × h","a × h","a + b + h","(a × b) / h","A"),
("Ondalık gösterimde 0,6 + 0,45 = ?","1,5","1,05","0,105","0,15","B"),
("Koordinat sisteminde (0, 0) noktasına ne denir?","x ekseni","y ekseni","Orijin","Koordinat","C"),
("Bir cismin hacminin hesabında hangi birim kullanılır?","cm²","m","cm³","kg","C"),
("Üçgenlerin benzerlik koşulu nedir?","Kenar uzunlukları eşittir","Açılar orantılı","Kenar uzunlukları orantılı ya da açıları eşit","Yalnızca açıları eşit","C"),
("6/9 kesrinin sadeleştirilmiş hâli nedir?","2/3","3/6","1/3","6/8","A"),
("Bir çemberin alanı formülü nedir?","π × r","2 × π × r","π × r²","2 × π × r²","C"),
("Oran ve orantıda 'doğru orantı' ne demektir?","Biri arttıkça diğeri azalır","Biri arttıkça diğeri de artar","Sabit kalır","Ters orantıdır","B"),
("Sayı doğrusunda -3 ile +3 arasındaki uzaklık kaçtır?","0","3","6","9","C"),
("Bir üçgenin dış açısı nedir?","İç açıların toplamı","Komşu iç açıyla birlikte 180° yapar","Diğer iki iç açının toplamına eşittir","Her zaman 90°'dir","C"),
("3 x 10⁴ = ?","30 000","300 000","3 000","30","A"),
("25'in karekökü nedir?","4","5","6","7","B"),
("Bir dikdörtgen prizma hacmi nasıl hesaplanır?","Uzun × Kısa","Uzun × Kısa × Yükseklik","2 × (U + K) × Y","U + K + Y","B"),
("Basit faiz formülü nedir?","F = A × n","F = (A × r × n) / 100","F = A / (r × n)","F = A + r + n","B"),
("Bir sayının %20'si 16 ise sayı kaçtır?","80","60","100","90","A"),
("0,001 = ?","1/100","1/1000","1/10","1/10000","B"),
("Düzgün altıgenin iç açıları toplamı kaç derecedir?","540°","720°","360°","480°","B"),
("(-7) - (-3) = ?","-10","-4","4","10","B"),
("3a + 2a = ?","5a","6a","a","5a²","A"),
("Bir elmanın 2/3'ünü yedim, kalan kısım oranı nedir?","1/4","1/3","2/3","3/2","B"),
("√144 = ?","11","12","13","14","B"),
("5 × (3 + 2) = ?","25","17","13","11","A"),
],

"Fen Bilimleri": [
("Hücre teorisine göre bütün canlılar neyi paylaşır?","Aynı RNA","Temel yapı birimi olarak hücreden oluşmaları","Aynı DNA dizisini","Aynı hücre şeklini","B"),
("Çekirdek hücrenin hangi işlevini yönetir?","Enerji üretimi","Protein sentezi ve DNA'nın korunması","Madde geçişi","Fotosentez","B"),
("Mitokondri hangi organelde bulunur?","Bitki hücresi","Hayvan hücresi","Hem bitki hem hayvan hücresi","Yalnızca bakteriler","C"),
("Klorofil nerede bulunur?","Mitokondri","Kloroplast","Çekirdek","Hücre zarı","B"),
("Fotosentez denklemi doğru olarak hangisidir?","CO₂ + H₂O + ışık → şeker + O₂","O₂ + H₂O → CO₂ + ışık","CO₂ + O₂ → H₂O + şeker","H₂O + ışık → CO₂ + şeker","A"),
("İnsan vücudunda en fazla bulunan element hangisidir?","Karbon","Oksijen","Hidrojen","Azot","B"),
("Kan dolaşımında akyuvarlar hangi işlevi yapar?","Oksijen taşır","Savunma sağlar","Besin taşır","Hormon üretir","B"),
("Aşağıdakilerden hangisi omurgasız bir canlıdır?","Balık","Kurbağa","Solucan","Kedi","C"),
("Işık hızı yaklaşık kaçtır?","3 × 10⁵ km/s","3 × 10³ km/s","3 × 10⁸ m/s her ikisi A ve C doğru","3 × 10² km/s","C"),
("Kuvvet birimi nedir?","Joule","Newton","Watt","Pascal","B"),
("Mevsimler neden oluşur?","Dünya'nın Güneş'e olan mesafesi değiştiğinden","Dünya'nın ekseninin eğik olması ve Güneş çevresinde dönmesinden","Ay'ın çekimi","Güneş'in ısısı değiştiğinden","B"),
("Kinetik enerji formülü nedir?","E = m × g × h","E = ½ × m × v²","E = P × t","E = F × d","B"),
("Bitkinin topraktan aldığı maddeler nelerdir?","Oksijen ve CO₂","Su ve mineraller","Şeker ve oksijen","CO₂ ve şeker","B"),
("Kan grupları kaç çeşittir?","2","3","4","5","C"),
("Periyodik tabloda elementler neye göre sıralanır?","Kütlelerine","Atom numaralarına","Renklerine","Büyüklüklerine","B"),
("Çözünürlük ne demektir?","Maddenin yoğunluğu","Belirli miktarda çözücüde çözünebilecek maksimum madde miktarı","Maddenin ağırlığı","Maddenin rengi","B"),
("Sinir hücresine ne denir?","Nöron","Eritrosit","Lökosit","Trombosit","A"),
("Basit makineler hangisini değiştirmez?","Kuvveti","Yönü","Yapılan işi","Mesafeyi","C"),
("Canlıların enerji üretimi için kullandığı madde nedir?","Su","Oksijen","Glikoz","Azot","C"),
("Ay'ın Dünya çevresinde bir tam tur atması kaç gün sürer?","7 gün","14 gün","27-28 gün","365 gün","C"),
("Isının transferi üç yolla olur. Hangisi bunlardan biri değildir?","İletim","Taşınım","Işıma","Yansıma","D"),
("Su molekülü hangi elementlerden oluşur?","Hidrojen ve Oksijen","Karbon ve Oksijen","Azot ve Hidrojen","Karbon ve Azot","A"),
("Erozyon nedir?","Su birikintisi","Toprak kayması ve aşınması","Dağ oluşumu","Volkanik patlama","B"),
("Elektrik devresinde voltaj neyi ölçer?","Akımı","Direnci","İki nokta arasındaki potansiyel farkı","Gücü","C"),
("Eklem türleri nelerdir? Hangisi örnek değildir?","Serbest eklem","Yarı hareketli eklem","Kemik eklem","Hareketsiz eklem","C"),
("Kırılma (refraksiyon) nedir?","Işığın yansıması","Işığın iki ortam arasında yön değiştirmesi","Işığın emilmesi","Işığın renklere ayrılması","B"),
("İskelet sistemi kaç görev üstlenir? Hangisi bunlardan biri değildir?","Vücudu desteklemek","Organları korumak","Hareket sağlamak","Sindirim yapmak","D"),
("Radyasyon nedir?","Ses dalgası","Elektromanyetik dalga ile enerji transferi","Sıvı akışı","Madde transferi","B"),
("Hangi madde organik bir bileşiktir?","NaCl","H₂O","C₆H₁₂O₆ (glikoz)","Fe","C"),
("Atmosferin hangi katmanı uçakların uçtuğu katmandır?","Troposfer","Stratosfer","Mezosfer","Termosfer","B"),
("Evrim teorisini ortaya atan bilim insanı kimdir?","Isaac Newton","Albert Einstein","Charles Darwin","Louis Pasteur","C"),
("Ses dalgaları ne tür dalgalardır?","Enine dalgalar","Boyuna dalgalar","Elektromanyetik dalgalar","Işık dalgaları","B"),
("Beyin kaç bölümden oluşur?","2","3","4","5","B"),
("Canlıların ortak özelliği hangisi değildir?","Büyüme","Solunum","Üreme","Işıkla beslenmek","D"),
("Bir maddenin erimesi için gerekli ısıya ne denir?","Erime ısısı","Buharlaşma ısısı","Donma ısısı","Yoğuşma ısısı","A"),
],

"Sosyal Bilgiler": [
("Osmanlı Devleti'ni kuran hangi aşirettir?","Selçuklu","Kayı boyu","Karakoyunlu","Akkoyunlu","B"),
("Osmanlı'nın başkenti sırasıyla nerelerden oluşur?","Söğüt-Bursa-Edirne-İstanbul","Bursa-Edirne-İstanbul-Ankara","Söğüt-Konya-İstanbul","Selçuklu-Bursa-İstanbul","A"),
("Fatih Sultan Mehmet İstanbul'u hangi yılda fethetti?","1453","1492","1299","1512","A"),
("Orta Çağ'da Avrupa'yı etkileyen veba salgınına ne denir?","Kolera","Kara Ölüm (Veba)","Tifüs","Grip","B"),
("Rönesans hareketi nerede başlamıştır?","Fransa","İtalya","İngiltere","Osmanlı","B"),
("Türkiye'nin en çok ithal ettiği ürünlerden biri hangisidir?","Buğday","Zeytin","Petrol","Çay","C"),
("Birinci Dünya Savaşı'nın başlangıç yılı nedir?","1914","1918","1919","1920","A"),
("Ticari faaliyet nedir?","Tarım yapmak","Mal ve hizmet alım satımı","Fabrika kurmak","Hayvancılık yapmak","B"),
("Küreselleşme ne demektir?","Bir ülkenin kendi içinde gelişmesi","Dünya ülkelerinin ekonomik, kültürel vb. alanlarda birbirine bağlanması","Çevresel felaket","Savaş","B"),
("Haçlı Seferleri hangi amaçla yapılmıştır?","Ticaret yollarını açmak","Kutsal toprakları (Kudüs'ü) ele geçirmek","Osmanlı'yı kurmak","Avrupa'yı korumak","B"),
("Reform hareketi hangi dinde gerçekleşmiştir?","İslamiyet","Hristiyanlık","Yahudilik","Budizm","B"),
("Türkiye'nin sanayisi en çok hangi bölgede yoğunlaşmıştır?","Karadeniz","Marmara ve Ege","İç Anadolu","Güneydoğu","B"),
("Coğrafi keşifler sonucunda ne oldu?","Orta Çağ başladı","Yeni kıtalar ve ticaret yolları keşfedildi","Rönesans sona erdi","İpek Yolu açıldı","B"),
("Tarih boyunca şehirlerin kurulduğu yerlerin ortak özelliği nedir?","Soğuk iklim","Su kaynaklarına yakınlık","Volkanik arazi","Çöl ortamı","B"),
("İnsan Hakları Evrensel Bildirgesi hangi yılda ilan edilmiştir?","1945","1948","1950","1960","B"),
("Türkiye'nin en önemli sanayi kolu hangisidir?","Balıkçılık","Tekstil ve otomotiv","Madencilik","Ormancılık","B"),
("Feodalite nedir?","Derebeylik sistemi","Cumhuriyet yönetimi","Ticaret ortaklığı","Kilise egemenliği","A"),
("Osmanlı'da devlet yönetimi nasıl adlandırılırdı?","Cumhuriyet","Monarşi (Saltanat)","Aristokrasi","Demokrasi","B"),
("Türkiye'nin AB'ye tam üyelik süreci ne zaman başlamıştır?","1963","1987","1999","2005","D"),
("Sanayi Devrimi nerede başlamıştır?","Fransa","Almanya","İngiltere","Amerika","C"),
("Osmanlı'da divan nedir?","Bir tür kanepe","Devlet işlerinin görüşüldüğü yüksek kurul","Saray bahçesi","Dini okul","B"),
("Göç sonucunda şehirlerde ne olur?","Nüfus azalır","Nüfus artar ve çeşitli sorunlar oluşabilir","Hiçbir değişim olmaz","Tarım gelişir","B"),
("İpek Yolu hangi iki kıtayı bağlıyordu?","Asya - Asya","Asya - Avrupa","Avrupa - Amerika","Afrika - Avrupa","B"),
("Türkiye'de en fazla kullanılan yenilenebilir enerji kaynağı hangisidir?","Güneş","Rüzgar","Su (hidroelektrik)","Jeotermal","C"),
("Medya ve basın özgürlüğü neden önemlidir?","Hükümeti güçlendirmek için","Bireylerin bilgiye ulaşmasını ve kamu denetimini sağlamak için","Ekonomiyi canlandırmak için","Ticareti artırmak için","B"),
("Ülkemizde yargı bağımsızlığı ne demektir?","Mahkemelerin hükümete bağlı olması","Mahkemelerin siyasi baskıdan bağımsız karar vermesi","Yargının meclis tarafından yönetilmesi","Yargının yürütme organına bağlı olması","B"),
("Kültürel miras nedir?","Gelecekte yapılacak binalar","Geçmiş kuşaklardan miras kalan değerler, eserler","Güncel sanat","Teknolojik ürünler","B"),
("Türkiye'de zorunlu eğitim kaç yıldır?","8","10","12","15","C"),
("Denge kuvvetler ilkesi neden önemlidir?","Demokratik yönetimde gücün tek elde toplanmaması için","Ekonomik büyüme için","Savaş kazanmak için","Nüfusu artırmak için","A"),
("Birleşmiş Milletler'in amacı nedir?","Tek bir hükümet kurmak","Uluslararası barış ve güvenliği korumak","Ticaret yapmak","Sadece refah sağlamak","B"),
("Osmanlı Devleti ne zaman dağılmıştır?","1918","1920","1922","1923","C"),
("Kültürel etkileşim nedir?","Savaş","Farklı kültürlerin birbirini etkilemesi","Salgın hastalık","Ticaret engeli","B"),
("İnsan hakları hangi ilkeleri kapsar?","Yalnızca siyasi haklar","Yaşam, özgürlük, eğitim, eşitlik gibi temel haklar","Yalnızca ekonomik haklar","Yalnızca dini haklar","B"),
("Türkiye'de belediyelerin görevi nedir?","Yurt dışı ilişkiler","Şehir içi hizmetler (su, ulaşım vb.)","Ordu yönetimi","Yargı","B"),
("Tarihî süreçte Anadolu önemli bir geçiş noktası olmuştur çünkü?","Çöl olduğu için","Asya ile Avrupa arasında köprü konumunda olduğu için","Soğuk iklimi nedeniyle","Denize uzak olduğu için","B"),
],

"İngilizce": [
("Which sentence uses 'there is' correctly?","There is two cats.","There is a dog in the garden.","There are a cat.","There is dogs.","B"),
("'Büyük' in English is?","small","tall","big","thin","C"),
("What is the past simple of 'go'?","goed","went","gone","going","B"),
("Which is a preposition?","run","beautiful","under","quickly","C"),
("'She ___ her homework every evening.' (do/does/did)","do","did","does","done","C"),
("What does 'library' mean?","Kitabevi","Kütüphane","Kafe","Okul","B"),
("'I ___ TV when the phone rang.' (was watching/is watching/watched)","watched","is watching","were watching","was watching","D"),
("Which is a question word?","and","but","where","because","C"),
("'They have ___ (much/many/a lot of) friends.'","much","lots","a lot of","many","D"),
("What does 'weather' mean?","Zaman","Hava durumu","Mevsim","Rüzgar","B"),
("'He is ___ (taller/more tall/tallest) than his brother.'","more tall","tallest","taller","tall","C"),
("Which is the correct possessive?","the bag of Ali","Ali bag","Ali's bag","Alis' bag","C"),
("'We ___ football yesterday.' (play/played/playing)","play","playing","plays","played","D"),
("What does 'healthy' mean?","Hasta","Sağlıklı","Zengin","Güçlü","B"),
("'I enjoy ___ (to swim/swimming/swim).'","to swim","swim","swam","swimming","D"),
("Which sentence is in present continuous?","She goes to school.","She went to school.","She is going to school.","She will go to school.","C"),
("What does 'borrow' mean?","Ödünç vermek","Satmak","Ödünç almak","Çalmak","C"),
("'___ she like pizza?' (Do/Does/Is)","Do","Is","Are","Does","D"),
("Which is an adjective?","run","beautiful","quickly","eat","B"),
("'I ___ (have never/have ever/has never) been to Paris.'","have ever","has never","has ever","have never","D"),
("What does 'journey' mean?","Tatil","Yolculuk","Macera","Eğlence","B"),
("'Can you ___ (speak/speaking/speaks) French?'","speaking","speaks","spoken","speak","D"),
("Which word means 'çevre'?","adventure","environment","subject","century","B"),
("'He ___ (has been/have been/is being) a teacher for 10 years.'","have been","is being","was being","has been","D"),
("What does 'ancient' mean?","Modern","Yeni","Eski, antik","Büyük","C"),
("'We should ___ (protect/protecting/protected) the environment.'","protecting","protected","protects","protect","D"),
("Which is a linking word showing contrast?","and","because","however","therefore","C"),
("'I prefer ___ (reading/to read/read) to watching TV.'","read","to reading","reads","reading","D"),
("What does 'solve' mean?","Oluşturmak","Çözmek","Bulmak","Aramak","B"),
("'By the time I arrived, she ___ (had left/has left/left).'","has left","left","leaves","had left","D"),
("Which sentence is correct?","She don't like coffee.","She doesn't like coffee.","She not like coffee.","She isn't like coffee.","B"),
("What does 'argue' mean?","Anlaşmak","Tartışmak","Gülmek","Ağlamak","B"),
("'I wish I ___ (could fly/can fly/could flew).'","can fly","could flew","fly","could fly","D"),
("Which word is a synonym for 'brave'?","afraid","coward","courageous","shy","C"),
("'He suggested ___ (going/to go/go) to the cinema.'","to go","go","goes","going","D"),
],

"Din Kültürü": [
("Hz. Muhammed İslam'ı kaç yaşında tebliğ etmeye başlamıştır?","30","35","40","45","C"),
("'İhlas' suresi kaç ayetten oluşur?","3","4","5","6","B"),
("Kur'an'ın indirilmeye başlandığı ay hangisidir?","Şevval","Şaban","Ramazan","Muharrem","C"),
("Cuma namazı kaç rekâttır? (Farz kısmı)","2","3","4","8","A"),
("İslam'da 'ahlak' kavramı ne anlama gelir?","Yalnızca ibadet","İyi huyu ve erdemlerin bütünü","Ekonomik başarı","Dini bilgi","B"),
("Hz. Yusuf kıssasının geçtiği sure hangisidir?","Yusuf Suresi","Bakara Suresi","Al-i İmran","Maide","A"),
("Kur'an'da en uzun sure hangisidir?","Fatiha","Al-i İmran","Bakara","Nisa","C"),
("'Salih amel' ne demektir?","Kötü davranış","İyi ve doğru amel, ibadet","Zekât","Dini söylem","B"),
("Hz. Süleyman'a hangi özellik verilmiştir?","Mucizevi iyileştirme","Hayvanların dilini anlama","Gök gürültüsü yapma","Denizi yarma","B"),
("İslam'da 'sabır' hangi durumla ilgilidir?","Yalnızca hastalıkta","Zorluklar karşısında dayanmak ve şükretmek","Yalnızca fakirlikte","Yalnızca namazda","B"),
("Kur'an'ın ilk vahiy ayeti hangi surenin başıdır?","Fatiha","Bakara","Alak","İhlas","C"),
("'İslam'ın şartları' nedir? Hangisi yanlıştır?","Kelime-i Şehadet","Namaz","Zekat","Hac","D"),
("Ramazan'da sahur vakti ne zamandır?","Gün ortası","Akşam","Gece yarısı","Tan yeri ağarmadan önce","D"),
("İslam tarihinde ilk halife kimdir?","Hz. Ömer","Hz. Ali","Hz. Ebubekir","Hz. Osman","C"),
("'Tövbe' ne anlama gelir?","Allah'ı unutmak","Hatalı davranışı bırakıp pişmanlık duyarak Allah'a dönmek","Namaz kılmamak","Oruç tutmak","B"),
("Hz. Nuh'un gemisini yaptığı olay neye bağlıdır?","Büyük kıtlık","Büyük tufan","Büyük yangın","Büyük deprem","B"),
("İslam'da 'fitne' ne anlama gelir?","Barış","Karışıklık ve bozgunculuk","Yardım","Huzur","B"),
("'Kader' inancı İslam akaidinde nedir?","Her şeyin tesadüf eseri olduğuna inanmak","Allah'ın her şeyi bildiğine ve takdir ettiğine inanmak","Kadere boyun eğmek","Çalışmamak","B"),
("Kuran'ı Kerim'i okumak ne tür bir ibadettir?","Müstehap","Mekruh","Vacip","Farz-ı kifaye","A"),
("'Hüsn-ü zan' ne demektir?","Kötü düşünme","İyi düşünme","Tarafsız düşünme","Eleştiri","B"),
("Hz. Peygamber'in torunu Hz. Hasan ve Hz. Hüseyin'in babası kimdir?","Hz. Ebubekir","Hz. Ömer","Hz. Ali","Hz. Osman","C"),
("'Emr-i bil maruf' ne demektir?","Kötülüğü yaymak","İyiliği emretmek","Zekât vermek","Dua etmek","B"),
("İslam'da yetim hakkı özellikle hangi ayette vurgulanmıştır?","Bakara 2","Nisa 10","Fatiha 1","İhlas 1","B"),
("'Takva' ne anlama gelir?","Pervasızlık","Allah'a karşı sorumluluk ve sakınma bilinci","Günahı önemsememek","Dua etmemek","B"),
("Hz. Eyyüp neyle imtihan edilmiştir?","Fakirlik","Hastalık ve sabır","Savaş","Sürgün","B"),
("'Şükür' nedir?","Allah'tan şikayet","Nimetler için Allah'a hamd ve minnettarlık","Oruç","Namaz","B"),
("İslam'da hangi davranış 'büyük günah' sayılır?","Namaz kaçırmak","Orucu yarıda bırakmak","Şirk (Allah'a ortak koşmak)","Yalan söylemek","C"),
("Kur'an'daki en uzun ayet hangisindedir?","Bakara 255 (Ayetel Kürsi)","Bakara 282","Fatiha 1","Nisa 1","B"),
("'Cömertlik' hangi kavramla ifade edilir?","Cimrilik","Hasislik","Sehâvet (Cömertlik)","Müsriflik","C"),
("'Münafık' kim demektir?","Açıkça kafir olan","Dışarıdan Müslüman görünüp içten inkâr eden","Günahkar Müslüman","Zeki kişi","B"),
("İslam'da evlilik neden teşvik edilir?","Yalnızca nüfus artırmak için","Aile kurumu, iffet ve toplumsal düzen için","Miras için","Ekonomik sebeplerle","B"),
("Hz. Lokman'ın oğluna nasıl bir tavsiyede bulunduğu Kur'an'da anlatılmaktadır. Bu tavsiyelerin özü nedir?","Zengin olma","Tevhid, namaz, güzel ahlak ve sabır","Hep çalışma","Tarım yapma","B"),
("'Tevekkül' ile 'tembellik' arasındaki fark nedir?","Farksızdır","Tevekkül sebebe sarılıp Allah'a güvenmektir; tembellik ise çalışmamaktır","Tevekkül pasiflik gerektirir","Her ikisi de aynıdır","B"),
("Kur'an'da Hz. Meryem adına bir sure var mıdır?","Hayır","Evet, Meryem Suresi","Evet ama başka adla","Sadece ayet var","B"),
("İslam'da 'hased' (kıskançlık) için hangisi söylenebilir?","Kıskançlık teşvik edilir","Kıskançlık sevapları yer","Kıskançlık haramdır","Kıskançlık makbuldür","C"),
],

}, # end of grade 6

# ══════════════════════════════════════════════════════════════════════
# 7. SINIF
# ══════════════════════════════════════════════════════════════════════
7: {

"Türkçe": [
("'Eğretileme (Metafor)' sanatı nedir?","İki şeyi aynı oldukları için karşılaştırmak","Bir şeyi başka bir şeyin ta kendisi olarak göstermek","Abartma","Kişileştirme","B"),
("Anlatıcı türleri arasında 'tanrısal bakış açısı' ne demektir?","Yalnızca dışarıdan izler","Her şeyi bilen, iç dünyalara giren anlatıcı","Yalnızca bir kişinin görüşü","Anlatıcı yoktur","B"),
("'Tersyüz ironi' sanatı ne demektir?","Abartma","Söylenenin tersini kastetmek","Benzetme","Kişileştirme","B"),
("Edebiyat tarihi açısından 'Tanzimat dönemi' ne zaman başlamıştır?","1699","1839","1908","1923","B"),
("'Örtmece' nedir?","Güçlü anlatım","Olumsuz veya kaba ifadeyi daha nazik söyleme","Kişileştirme","Benzetme","B"),
("Türk edebiyatında 'halk şiiri' için hangisi doğrudur?","Divan şiiriyle aynıdır","Sade dil, hece ölçüsü kullanılır","Aruz ölçüsüyle yazılır","Yalnızca yazılı biçimde aktarılır","B"),
("'Akıl yürütme' türü olan 'tümdengelim' nedir?","Özelden genele gitmek","Genelden özele gitmek","Duygu bildirmek","Hipotez kurmak","B"),
("Cumhuriyet dönemi Türk edebiyatında öne çıkan isim hangisidir?","Fuzuli","Yunus Emre","Orhan Kemal","Evliya Çelebi","C"),
("'Gösterme yöntemi' (show don't tell) yazarlık tekniği ne demektir?","Duyguları doğrudan açıklamak","Olayları ve duyguları eylem ve diyalogla hissettirmek","Kısa tutmak","Yorum yapmak","B"),
("Epik şiir ne anlatır?","Aşk","Kahramanlık ve savaş destanları","Doğa","Hüzün","B"),
("Türk sözlü edebiyatında 'destan' türüne örnek hangisidir?","Mesnevi","Oğuz Kağan Destanı","Divân-ı Hikmet","Kalevala","B"),
("Bağımsız cümlelerde sıralama bir 'koordinat cümlesi' oluşturur. Bu nasıl yapılır?","Bağlaçsız","Bağlaçla ya da noktalama ile","Eylemle","Yalnızca virgülle","B"),
("'Eleştirel düşünme' için hangisi doğrudur?","Her şeyi kabul etmek","Kanıtlara dayanarak değerlendirme yapma","Duygusal tepki","Amacı olmayan soru sorma","B"),
("'Anlatı üçgeni' (Freytag) hangi ögeyi kapsamaz?","Giriş","Düğüm","Çözüm","Tema","D"),
("Türkçede fiil çatısı nedir?","Fiilin anlamı","Fiilin özne ve nesneyle ilişki biçimi","Fiilin kipi","Fiilin eki","B"),
("Büyük Selçuklu Devleti'nin resmi yazışma dili neydi?","Türkçe","Farsça","Arapça","Moğolca","B"),
("'Deneme' türü edebiyatta ne anlama gelir?","Bilimsel makale","Yazarın kişisel görüşlerini özgürce açıkladığı kısa yazı","Roman","Şiir","B"),
("'Kıta' ve 'dörtlük' arasındaki fark nedir?","Aynı şeydir","Dörtlük halk şiirinde, kıta divan şiirinde kullanılır","Kıta üç dizedir","Dörtlük beş dizedir","B"),
("Serbest şiir nedir?","Uyaklı şiir","Ölçü ve kafiye zorunluluğu olmayan şiir","Yalnızca hece ölçülü","Yalnızca aruz ölçülü","B"),
("'Özgün' anlatım ne demektir?","Başkasından kopyalanmış","Yazarın kendine özgü kişisel tarzı","Akademik anlatım","Dini anlatım","B"),
("'Pekiştirme sıfatı' nedir?","Sıfatın bir nesneyi belirtmesi","Anlam güçlendirilen sıfat (ipek gibi yumuşak vb.)","Sıfatın zıttı","Sıfatın çoğulu","B"),
("Türk edebiyatında 'mesnevi' nedir?","Halk şiiri türü","Her beyti kendi içinde kafiyeli uzun manzum anlatı","Roman türü","Dil bilgisi terimi","B"),
("'Öğretici metin' ne anlama gelir?","Hayal ürünü","Okuyucuya bilgi veya beceri kazandırmayı amaçlayan metin","Yalnızca şiir","Yalnızca roman","B"),
("'Ses akışı' (prozodi) ne anlama gelir?","Ses yüksekliği","Şiirde ritim, vurgu ve ses düzenlemesi","Ses hızı","Ses tonu","B"),
("Türkçede yansıma sözcük örneklerinden biri hangisidir?","güneş","kitap","şırıl şırıl","araba","C"),
("'Sözcük türetme' için hangisi doğru değildir?","Ön ek ekleyerek","Son ek ekleyerek","Bileşik sözcük kurarak","Sözcüğü çevirerek","D"),
("Divan edebiyatında 'gazel' kaç beyitten oluşur?","2-3","5-15","16-20","30-40","B"),
("'Anlatıcı sesi' ne demektir?","Yazarın sesi","Metindeki anlatıcının benzersiz ifade ve tonu","Okuyucunun sesi","Karakterin sesi","B"),
("Türk edebiyatında 'Servet-i Fünûn' dönemi ne zaman?","1839","1896","1923","1960","B"),
("'Yalın kip' nedir?","Şart modu","Bildirme kiplerinden biri olan ve kesin eylem bildiren","Dilek kipi","Emir kipi","B"),
("Türkçede 'ikileme' nedir?","Yabancı sözcük","Anlam kuvvetlendirmek için iki sözcüğün tekrarlanması","Alıntı sözcük","Bağlaç","B"),
("Şiirde 'redif' nedir?","Uyaktan önce gelen aynı ses","Uyaktan sonra gelen aynı ses ya da sözcük","Ölçü türü","Dize","B"),
("'Mizah' nedir?","Üzüntü","Güldürme, eğlendirme, zararsız şakayı kapsayan edebiyat türü","Korku","Şiddet","B"),
("'Edebî kişilik' nedir?","Yazarın fiziksel görünümü","Yazarın kendine özgü üslubu ve sanat anlayışı","Romanın karakteri","Metindeki kişi","B"),
("'Eril-dişil' ayrımı Türkçede var mıdır?","Evet, tüm dillerdeki gibi","Hayır, Türkçede dilbilgisel cinsiyet yoktur","Yalnızca yazılı Türkçede var","Eski Türkçede vardı","B"),
],

"Matematik": [
("Doğru orantıda y = kx ilişkisinde k neyi temsil eder?","y-kesişim noktasını","Orantı sabitini","Toplamı","Farkı","B"),
("Ters orantıda x × y = k ise x 2 katına çıkarsa y ne olur?","2 katına çıkar","Yarıya iner","Değişmez","4 katına çıkar","B"),
("2x + 5 = 15 denkleminde x = ?","4","5","6","7","B"),
("(3x - 2)(x + 4) çarpımı nedir?","3x² + 10x - 8","3x² + 8x - 8","3x² - 10x + 8","3x² + 14x - 8","A"),
("Bir eşitsizlikte x > 3 çözüm kümesi hangisidir?","x = 3","x < 3","3'ten büyük tüm sayılar","3'ten küçük tüm sayılar","C"),
("Veri setinde mod ne demektir?","Ortanca değer","En sık geçen değer","Ortalamanın karesi","Toplam bölü adet","B"),
("İki tam sayının ortak böleni nedir? OBEB'in anlamı?","En büyük ortak bol","En küçük ortak kat","En büyük ortak bölen","En küçük ortak bölen","C"),
("Aritmetik ortalama formülü nedir?","Veriler toplamı × adet","Veriler toplamı ÷ adet","Veriler ortancası","En büyük + en küçük","B"),
("3(x + 2) = 18 ise x = ?","4","5","6","3","A"),
("Bir sayının yüzde kaçıdır? 40'ın %15'i = ?","6","5","8","4","A"),
("Medyan ne demektir?","Ortalama","Sıralı veride ortadaki değer","En sık tekrarlanan","En büyük değer","B"),
("Olasılık hesabında P(A) + P(A') = ?","0","1","2","P(A)","B"),
("Bir zarın 6 gelme olasılığı nedir?","1/5","1/6","2/6","1/3","B"),
("Koordinat düzleminde noktalar arası uzaklık formülü nedir?","d = x₂-x₁","d = √((x₂-x₁)²+(y₂-y₁)²)","d = (y₂-y₁)","d = x₂+y₂","B"),
("5x - 3 = 2x + 6 denkleminde x = ?","2","3","1","9","B"),
("İki kesirin toplanması için önce ne yapılır?","Payları çarpılır","Ortak payda bulunur","Paydalara bakılmaz","Paydalar çarpılır","B"),
("Kümeler arası birleşim (A ∪ B) ne demektir?","A'ya ait olan her şey","A veya B'de bulunan tüm elemanlar","Yalnızca A'da bulunanlar","A ve B'nin ortak elemanları","B"),
("Bir küpün hacim formülü nedir?","6a²","a³","4a²","3a","B"),
("Çemberin çevresi = ?","π × r²","2πr","πr","4πr","B"),
("Bileşik olay olasılığı P(A ve B) bağımsız olaylar için nasıl hesaplanır?","P(A) + P(B)","P(A) × P(B)","P(A) - P(B)","P(A) / P(B)","B"),
("Veri dağılımında 'aralık' nedir?","Ortalama","En büyük ile en küçük arasındaki fark","Mod","Medyan","B"),
("Negatif × Negatif = ?","Negatif","Sıfır","Pozitif","Belirsiz","C"),
("Bir dairenin alanı r = 7 cm ise (π ≈ 3,14)?","153,86 cm²","43,96 cm","21,98 cm","307,72 cm²","A"),
("Köklerin sadeleştirilmesi: √50 = ?","5√2","10√2","2√5","25√2","A"),
("Üslü sayıda aˣ × aʸ = ?","a^(x+y)","a^(xy)","a^(x-y)","a^(x/y)","A"),
("Denklem sistemini çözmek: x + y = 7 ve x - y = 3 ise x = ?","4","5","3","2","B"),
("Yüzde artış formülü nedir?","Artış × 100 / Eski değer","Yeni × 100 / Eski","(Yeni - Eski) / Eski × 100","Eski - Yeni","C"),
("Kesirli denklem: 1/x = 3/9 ise x = ?","2","3","4","6","B"),
("Pisagor teoremi nedir?","a + b = c","a² + b² = c²","a × b = c","a / b = c","B"),
("Bir fonksiyonda f(x) = 2x + 3 ise f(4) = ?","11","10","12","8","A"),
("Çarpanlara ayırma: x² - 9 = ?","(x+3)(x+3)","(x-3)(x-3)","(x+3)(x-3)","x(x-9)","C"),
("Düzgün altıgenin iç açısı kaç derecedir?","108°","120°","135°","140°","B"),
("3 kapı seçeneğinden birini seçme olasılığı?","1/2","1/3","2/3","3/3","B"),
("Karmaşık denklem: 2(x-3) + 4 = 10 → x = ?","5","6","7","4","A"),
("Hacim: Silindir V = ?","π × r² × h","2πr × h","π × r + h","πr","A"),
],

"Fen Bilimleri": [
("Newton'un hareket yasaları kaç tanedir?","2","3","4","5","B"),
("İş formülü nedir?","W = F + d","W = F × d","W = F / d","W = F - d","B"),
("Güç formülü nedir?","P = W × t","P = W / t","P = F × t","P = d / t","B"),
("Elektrik devrelerinde dirençler seri bağlandığında toplam direnç nasıl bulunur?","1/R = 1/R₁+1/R₂","R = R₁ × R₂","R = R₁ + R₂","R = R₁ - R₂","C"),
("Paralel devrede gerilim nasıldır?","Her kolda farklı","Her kolda aynı","Sıfır","Sonsuz","B"),
("Ohm kanunu nedir?","V = I + R","V = I × R","V = I / R","V = I² × R","B"),
("Kuvvet birimi nedir?","Joule","Watt","Newton","Pascal","C"),
("İş birimi nedir?","Newton","Watt","Joule","Pascal","C"),
("Maddenin ısıl kapasitesi nedir?","1 g maddeyi 1°C ısıtmak için gereken ısı","1 kg maddeyi 1°C ısıtmak için gereken ısı","Maddenin toplam ısısı","Maddenin yoğunluğu","B"),
("DNA nerede bulunur?","Mitokondri","Kloroplast","Hücre çekirdeği","Hücre zarı","C"),
("Eşeyli üremede oluşan hücrelere ne denir?","Spor","Gamete","Sperm ve yumurta (eşey hücreleri)","Zigot","C"),
("Mayoz bölünme sonucunda kaç hücre oluşur?","2","3","4","8","C"),
("Mitoz bölünme neden yapılır?","Üreme","Büyüme ve onarım","Enerji üretimi","Fotosentez","B"),
("Genetikte 'dominant' gen ne demektir?","Gizli kalan gen","Etkisini her zaman gösteren gen","Mutasyona uğramış gen","Resesif gen","B"),
("Periyodik tabloda atomlar sıralanırken esas alınan nedir?","Kütle","Atom numarası","Renk","Büyüklük","B"),
("Alkali metaller periyodik tablonun hangi grubundadır?","Grup 17","Grup 1","Grup 18","Grup 2","B"),
("İyon nedir?","Proton sayısı değişmiş atom","Nötron sayısı değişmiş atom","Elektron sayısı değişmiş, yük kazanmış atom","Radyoaktif atom","C"),
("Kovalent bağ nasıl oluşur?","Elektron transferiyle","Elektron ortaklaşmasıyla","Proton paylaşımıyla","Nötron alışverişiyle","B"),
("Asit-baz reaksiyonunda oluşan ürünler nelerdir?","Tuz ve su","Gaz ve su","Asit ve baz","Yalnızca tuz","A"),
("İnsan genomu kaç çift kromozom içerir?","22","23","24","46","B"),
("Işığın dalga boyuna göre rengi değişir. Mor ışığın dalga boyu nasıldır?","En uzun","Kırmızıdan uzun","En kısa","Yeşilden kısa","C"),
("Kütle çekim yasasına göre iki cismin arasındaki çekim kuvveti neyle artar?","Uzaklıkla","Kütlelerle","Hızlarıyla","Hacimlerle","B"),
("'Momentum' nedir?","Kütlenin küpü","Kütle × hız","Kuvvet × zaman","Ağırlık × yükseklik","B"),
("Ses frekansı yükselince ses nasılır?","Alçalır","İncelir (tizleşir)","Değişmez","Kesik olur","B"),
("Güneş enerjisi üretilen enerjiyi nasıl aktarır?","Moleküller","Radyasyon (elektromanyetik)","İletim","Taşınım","B"),
("Yoğunluk ve suyun yoğunluğu ilişkisi: Yoğunluğu 0,7 g/cm³ olan madde suda ne yapar?","Batar","Yüzer","Asılı kalır","Erir","B"),
("Bitkilerde büyüme hormonu nedir?","Adrenalin","Insülin","Oksin","Testosteron","C"),
("Büyük patlama (Big Bang) teorisi neyi açıklar?","Evrenin sonu","Evrenin başlangıcı ve genişlemesi","Güneş'in oluşumu","Atomun bölünmesi","B"),
("Elektromanyetik dalgalar arasında en kısa dalgaboylu olan nedir?","Radyo dalgaları","Kızılötesi","Gamma ışını","Morötesi","C"),
("Sürtünme kuvvetinin avantajı nedir?","Hiç avantajı yoktur","Yürümeyi ve frenaj yapmayı sağlar","Enerji kaybeder","Hızlanmayı sağlar","B"),
("Maddenin sıvıdan gaz hale geçişine ne denir?","Donma","Erime","Buharlaşma","Yoğuşma","C"),
("Doğal seçilim teorisine göre hangisi hayatta kalır?","Büyük bireyler","Çevreye en iyi uyum sağlayanlar","En hızlılar","En agresifler","B"),
("Ampermetre devreye nasıl bağlanır?","Paralel","Seri","İkisi de olur","Bağlanmaz","B"),
("Kimyasal tepkimelerde madde korunumu yasasına göre?","Kütleler eşit olmaz","Tepkiyen maddelerin toplam kütlesi, ürünlerin toplam kütlesine eşittir","Ürünler azalır","Kütleler artar","B"),
("İnsan gözünde retina nerede bulunur?","Gözün önünde","Gözün arka duvarında","Mercekte","Kornea'da","B"),
],

"Sosyal Bilgiler": [
("Osmanlı'nın en uzun süre hüküm süren padişahı hangisidir?","Kanuni Sultan Süleyman","Yavuz Sultan Selim","II. Abdülhamit","I. Ahmet","C"),
("Viyana kuşatmaları Osmanlı için hangi önemi taşır?","Osmanlı'nın zirve ve duraksama noktasıdır","Osmanlı'nın kuruluşu","Osmanlı'nın çöküşü","Sadece askeri","A"),
("Rönesans'ın temelinde ne yatmaktadır?","Din merkezli düşünce","İnsan merkezli (hümanist) düşünce","Doğa merkezli düşünce","Ticaret merkezli düşünce","B"),
("Fransız Devrimi'nin sloganı nedir?","Özgürlük, Eşitlik, Kardeşlik","Çalışmak, Atatürk, Türkiye","İmparatorluk, Kilise, Kral","Toprak, Halk, Para","A"),
("Sanayi Devrimi'nin sosyal sonucu nedir?","Köy nüfusu arttı","Şehirleşme ve işçi sınıfının ortaya çıkması","Tarım gelişti","Nüfus azaldı","B"),
("Osmanlı'da Tanzimat Fermanı kaç yılında ilan edildi?","1839","1876","1908","1923","A"),
("Çanakkale Savaşı hangi yılda yaşandı?","1914","1915","1916","1917","B"),
("Hukuk devleti ne demektir?","Yalnızca kuvvetlilerin hakim olduğu devlet","Hukukun üstün olduğu, herkesin yasalara tabi olduğu devlet","Monarşi","Dini devlet","B"),
("'Kuvvetler ayrılığı ilkesi' ne anlama gelir?","Tek elde toplanan güç","Yasama, yürütme ve yargının birbirinden bağımsız olması","Sadece yargı","Sadece parlamento","B"),
("Coğrafi keşifler hangi sonuçları doğurdu?","Yalnızca Avrupa zenginleşti","Avrupa zenginleşti, sömürgecilik başladı, ticaret yolları değişti","Osmanlı güçlendi","Asya gelişti","B"),
("Birinci Dünya Savaşı'nda Osmanlı hangi tarafta yer almıştır?","İtilaf (İngiltere vb.)","İttifak (Almanya vb.)","Tarafsız","Yalnız savaştı","B"),
("Matbaanın bulunmasının önemi nedir?","Üretim arttı","Bilginin hızla yayılması","Ticaret gelişti","Ulaşım kolaylaştı","B"),
("İnsan hakları için 'evrensel' neden denir?","Çünkü herkese uygulanır","Çünkü sadece bazı ülkelere","Çünkü yalnızca Avrupa'ya","Çünkü zenginlere","A"),
("Küresel ekonomik sorunlar arasında 'yoksulluk' neden önemlidir?","Sadece ekonomik","Eğitim, sağlık ve insan haklarını etkiler","Yalnızca Afrika'da","Çözümsüzdür","B"),
("Sürdürülebilir kalkınma ne demektir?","Hızla büyüme","Bugünün ihtiyaçlarını, gelecek nesillerin imkânlarını zayıflatmadan karşılamak","Yalnızca doğayı korumak","Sanayi durdurmak","B"),
("Türkiye'nin insan hakları alanındaki temel belgesi hangisidir?","Lozan","Misak-ı Millî","Türkiye Cumhuriyeti Anayasası","Teşkilat-ı Esasiye","C"),
("Avrupa'da Orta Çağ'ı niteleyen özellik nedir?","Demokrasi","Feodalizm ve kilise egemenliği","Sanayi","Cumhuriyet","B"),
("Osmanlı'da 'millet sistemi' ne anlama gelir?","Dini toplulukların kendi işlerini yönetmesi","Ulus devlet","Eğitim sistemi","Askeri örgütlenme","A"),
("Balkanlarda milliyetçilik hareketleri Osmanlı'yı nasıl etkiledi?","Güçlendirdi","Toprak kayıplarına yol açtı","Ekonomiyi geliştirdi","Tarihine katkı sağladı","B"),
("İkinci Dünya Savaşı'nın sonunda kurulan uluslararası örgüt hangisidir?","NATO","Birleşmiş Milletler","AB","IMF","B"),
("Atatürk'ün 'Tam Bağımsızlık' ilkesi ne anlama gelir?","Sadece ekonomik bağımsızlık","Mali, siyasi ve her alanda dışa bağımlı olmamak","Askeri bağımsızlık","Kültürel bağımsızlık","B"),
("'Uluslararası hukuk' kimler için geçerlidir?","Yalnızca güçlü ülkeler","Tüm devletler","Yalnızca Batı","Yalnızca BM üyeleri","B"),
("Osmanlı'da ekonomik çöküşün temel nedenleri nelerdir?","Aşırı refah","Sürekli savaşlar ve kapitülasyonlar","Deniz ticaretinin gelişmesi","Tarımsal bolluk","B"),
("Coğrafi bölgelerin belirlenmesinde esas alınan nedir?","Yüzey şekli","Doğal, beşeri ve ekonomik özellikler bir arada","Yalnızca iklim","Yalnızca tarih","B"),
("'Millî Mücadele'nin simgesi olan antlaşma hangisidir?","Sevr","Lozan","Mondros","Mudanya","B"),
("Türkiye'de cumhurbaşkanlığı görev süresi nedir?","4 yıl","5 yıl","6 yıl","7 yıl","B"),
("Coğrafi bölgelerin sınırları nasıldır?","Kesin siyasi sınır","Geçiş bölgesiyle birbirinden ayrılır","Denizlerle ayrılır","Dağlarla kesin ayrılır","B"),
("Osmanlı'da Divan-ı Hümayun'da alınan kararlar hangi konuları kapsar?","Yalnızca din","Devlet yönetimi, adalet ve dış ilişkiler","Yalnızca askerlik","Yalnızca ekonomi","B"),
("Demokratikleşme sürecinde 'çoğulculuk' ne demektir?","Tek partili yönetim","Farklı görüşlerin eşit haklara sahip olması","Çoğunluğun her şeye karar vermesi","Azınlıkların baskı altına alınması","B"),
("Nüfus sayımları neden yapılır?","Askeri amaçlarla","Devlet planlaması, eğitim, sağlık için nüfus bilgisi elde etmek","Yalnızca vergi","Yalnızca seçim","B"),
("Türkiye'de yerel yönetimler hangileridir?","Yalnızca belediyeler","Belediyeler, il özel idareleri ve köy muhtarlıkları","Yalnızca köyler","Yalnızca iller","B"),
("Balkan savaşları Osmanlı'ya hangi etkiyi yapmıştır?","Toprak kazandı","Avrupa'daki toprakların büyük çoğunluğunu kaybetti","Güçlendi","Genişledi","B"),
("Sanayi devriminin icat ettiği buhar makinesi kimin eseridir?","James Watt","Thomas Edison","Alexander Bell","Nikola Tesla","A"),
("Çanakkale'nin stratejik önemi nedir?","Ticaret yolu","Boğaz ve İstanbul'a giriş kapısı","Askeri üs","Kültür merkezi","B"),
("Osmanlı İmparatorluğu'nun en geniş sınırlara ulaştığı dönem hangisidir?","I. Osman","Kanuni Sultan Süleyman","Yıldırım Bayezit","II. Selim","B"),
],

"İngilizce": [
("'I wish I ___ harder.' (studied/study/had studied)","study","studies","studied","had studied","D"),
("What does 'although' mean?","çünkü","ama/her ne kadar","eğer","bundan sonra","B"),
("'She ___ the book by 8 PM.' (will have finished/finishes/finished)","finishes","finished","finish","will have finished","D"),
("'If it rains, we ___ stay inside.' (would/will/shall)","would","shall","should","will","D"),
("What does 'responsibility' mean?","sorumluluk","fırsat","ilgi","görev","A"),
("'They ___ football for two hours.' (have been playing/have played/played)","played","have played","play","have been playing","D"),
("Which is a relative pronoun?","because","however","who","although","C"),
("'The house ___ (was built/built/has built) in 1900.'","built","has built","build","was built","D"),
("What does 'encourage' mean?","cesaretlendirmek","engellemek","korumak","izlemek","A"),
("'She asked me where ___ (I lived/did I live/I live).'","did I live","I live","I had lived","I lived","D"),
("What does 'valuable' mean?","değersiz","pahalı","değerli","önemli","C"),
("'He said that he ___ (would come/will come/comes) the next day.'","will come","comes","come","would come","D"),
("'Not only ___ he late, but he also forgot his bag.' (was/did/were)","did","were","is","was","D"),
("What does 'pollution' mean?","kirlilik","temizlik","hava","su","A"),
("'I ___ (had been working/have worked/worked) for 3 hours before she arrived.'","have worked","worked","has worked","had been working","D"),
("'She is looking forward ___ (to seeing/to see/see) you.'","to see","see","seeing","to seeing","D"),
("What does 'curious' mean?","meraklı","sabırsız","korkmuş","heyecanlı","A"),
("'Despite the rain, ___ (we went/we go/going) out.'","we go","going","to go","we went","D"),
("Which sentence is in passive voice?","She reads the book.","The book was read by her.","She has read the book.","She will read the book.","B"),
("What does 'enormous' mean?","küçük","devasa büyük","hızlı","yavaş","B"),
("'They have been friends ___ (since/for/from) 2015.'","for","from","by","since","D"),
("'I would rather ___ (stay/staying/to stay) at home.'","staying","to stay","stayed","stay","D"),
("What does 'grateful' mean?","minnettar","şikayetçi","yorgun","hevesli","A"),
("'By next year, she ___ (will have graduated/graduates/graduated).'","graduates","graduated","graduate","will have graduated","D"),
("What does 'conflict' mean?","çatışma, anlaşmazlık","barış","anlaşma","ittifak","A"),
("'He suggested that she ___ (should take/takes/took) the exam.'","takes","took","take","should take","D"),
("What does 'reliable' mean?","güvenilmez","güvenilir","hızlı","yavaş","B"),
("'As soon as I arrive, I ___ (will call/would call/called) you.'","called","would call","call","will call","D"),
("What does 'approximately' mean?","kesinlikle","yaklaşık olarak","tamamen","hiçbir zaman","B"),
("'The children were made ___ (to clean/cleaning/clean) their rooms.'","cleaning","clean","cleaned","to clean","D"),
("What does 'innovative' mean?","yenilikçi","eskimiş","geleneksel","rutin","A"),
("'She is ___ (more talented/most talented/talented) than her sister.'","most talented","talented","the most talented","more talented","D"),
("What does 'eliminate' mean?","eklemek","korumak","ortadan kaldırmak","üretmek","C"),
("'He insisted on ___ (going/to go/go) alone.'","to go","go","goes","going","D"),
("What does 'compassionate' mean?","merhamet dolu","bencil","sert","ilgisiz","A"),
],

"Din Kültürü": [
("Büyük İslam düşünürü İbn-i Sina hangi alanda ünlüdür?","Matematik","Tıp ve felsefe","Astronomi","Tarih","B"),
("'Ahlâk-ı Alâî' eserinin yazarı kimdir?","Kınalızade Ali Efendi","Farabi","İbn Rüşd","Gazali","A"),
("İslam'da 'şura' ne anlama gelir?","Tek adam yönetimi","İstişare, danışma","Vergi","İslam hukuku","B"),
("'İhtilafu ümmeti rahme' hadisinin anlamı nedir?","Birlik zorunludur","Görüş ayrılığı topluma rahmet olabilir","Anlaşmazlık yasaktır","Fikir birliği şarttır","B"),
("Hz. Rumi (Mevlana) hangi şehirde yaşamış ve eserler vermiştir?","İstanbul","Konya","Bursa","Kahire","B"),
("'Fıkıh' ilmi ne anlama gelir?","Kuran tefsiri","İslam'ın hukuki hükümlerini inceleyen ilim","Kelam","Tasavvuf","B"),
("İmam-ı Azam Ebu Hanife hangi mezhepte öncüdür?","Maliki","Şafii","Hanefi","Hanbeli","C"),
("'Kelam' ilmi neyi inceler?","İslam hukuku","İslam inanç esaslarını akli yöntemlerle inceleyen ilim","Hadis","Tefsir","B"),
("Tasavvufta 'gönül eğitimi' için kullanılan yönteme ne denir?","İlim","Nefs terbiyesi","Fıkıh","Kelam","B"),
("Yunus Emre'nin şiirlerinde öne çıkan tema nedir?","Savaş ve kahramanlık","Allah sevgisi, insan sevgisi, gönül","Tarih","Siyaset","B"),
("İslam'da 'emanet' kavramı ne demektir?","Borç almak","Güvenilir olmak ve sorumlulukları yerine getirmek","Sadaka vermek","Hediye almak","B"),
("'Hadis-i Şerif' ne anlama gelir?","Kur'an ayeti","Hz. Peygamber'in söz, eylem veya onayları","Sure","Dua","B"),
("İslam medeniyetinde ilk rasathaneyi kuran kimdir?","Uluğ Bey","İbn Batuta","Biruni","Harezmi","A"),
("'Tefsir' ilmi nedir?","Hadis açıklaması","Kur'an ayetlerini açıklama ve yorumlama","Fıkıh hükümleri","Tasavvuf yolu","B"),
("'Siyer' nedir?","Kur'an bölümü","Hz. Peygamber'in hayatını anlatan ilim","İslam hukuku","Dua kitabı","B"),
("'Cihad' kavramının geniş anlamı nedir?","Yalnızca savaş","Allah yolunda her türlü çaba ve mücadele","Yalnızca ibadet","Yalnızca okumak","B"),
("İslam'da 'riya' nedir?","Güzel davranış","İbadetleri başkalarına göstermek için yapmak","Dua etmek","Sadaka vermek","B"),
("Osmanlı medreselerinde okutulan en önemli ders neydi?","Tarih","Fıkıh ve Kur'an ilimleri","Matematik","Coğrafya","B"),
("'Müezzin' kimdir?","Cami yöneticisi","Ezan okuyan kişi","İmam","Vaiz","B"),
("'Sadakat' ile 'sıdk' arasındaki fark nedir?","Aynı anlama gelir","Sadakat bağlılık, sıdk ise dürüstlük ifade eder","Sadakat dini bir kavramdır","Sıdk sadaka demektir","B"),
("İslam'da ilim öğrenmek farz mı kabul edilir?","Hayır","Evet, 'İlim öğrenmek her Müslümana farzdır' hadisiyle","Yalnızca alimler için","Yalnızca erkekler için","B"),
("'Taklit' ve 'tahkik' nedir? Dini açıdan farkları nedir?","Aynıdır","Taklit körü körüne uymak, tahkik araştırarak inanmak","Taklit daha iyidir","İkisi de aynı değerdedir","B"),
("'Cuma hutbesi' zorunlu mudur?","Hayır","Evet, cuma namazının geçerli olması için şarttır","İsteğe bağlıdır","Yalnızca Ramazan'da","B"),
("İslam'daki 'vedia' kavramı nedir?","Miras","Emanet bırakılan mal","Zekât","Alışveriş","B"),
("Osmanlı vakıf sistemi neye hizmet eder?","Vergi toplamak","Toplumun eğitim, sağlık, hayır gibi ihtiyaçlarını karşılamak","Askeri hizmet","Dini denetim","B"),
("'Maşallah' ifadesi hangi anlama gelir?","Allah'a şükür","Allah'ın dilediği olmuş (takdir ve hayret)","Allah bağışlasın","Allah korusun","B"),
("Farabi'nin felsefedeki önemi nedir?","Astronomi","Doğu-Batı felsefesinibir arada değerlendiren ilk İslam filozofu","Matematik","Hadis","B"),
("İslam dünyasında ilk hastaneler nerede kurulmuştur?","Avrupa","Çin","İslam dünyasında (Abbasiler döneminde Bağdat'ta)","Amerika","C"),
("'Hüsn-ü ahlak' ne anlama gelir?","Kötü ahlak","Güzel ve üstün ahlak","Ortalama ahlak","Dini tartışma","B"),
("'Mürekkep günah' ne demektir?","Tek günah","Birden fazla günahın iç içe geçtiği durum","Küçük günah","Büyük günah","B"),
("İslam'ın barış ve selamet sözcükleriyle ortak kökü hangisidir?","Allah","Selam (silm)","İman","Ahlak","B"),
("Hadis ilminde 'müttefekun aleyh' ne demektir?","Yalnızca Buhari'nin rivayeti","Hem Buhari hem Müslim'in ittifakla rivayet ettiği hadis","Zayıf hadis","Uydurma hadis","B"),
("'Marufu emr, münkeri nehy' ne anlama gelir?","Kötülüğü yay","İyiliği emret, kötülüğü yasakla","Sadece dua et","Yalnızca ibadet et","B"),
("'Adalet' ve 'hakkaniyet' arasındaki fark nedir?","Aynıdır","Adalet eşit muamele, hakkaniyet ise ihtiyaca göre adalet","Hakkaniyet daha az önemlidir","Adalet bireyseldir","B"),
("Kur'an'da hangi surede Hz. Yusuf'un hikayesi tam anlatılır?","Kehf","Meryem","Yusuf","İbrahim","C"),
],

}, # end of grade 7

# ══════════════════════════════════════════════════════════════════════
# 8. SINIF
# ══════════════════════════════════════════════════════════════════════
8: {

"Türkçe": [
("'Cumhuriyet dönemi Türk edebiyatı' hangi yılda başlar?","1839","1896","1923","1908","C"),
("'Varoluşçuluk' edebiyat akımında temel düşünce nedir?","Toplumsal sorunlar","Bireyin varoluşunu ve özgürlüğünü sorgulamak","Doğa tasvirlerini öne çıkarmak","Dinî değerleri yüceltmek","B"),
("'Öz şiir' akımı nasıl tanımlanır?","Anlamı önemli, biçim ikinci planda","Ses ve müzik ön plana çıkar, anlam geri planda","Her ikisi eşit","Yalnızca biçim önemli","B"),
("Türk romanında 'toplumsal gerçekçilik' hangi döneme aittir?","Tanzimat","Servet-i Fünûn","1940-50 sonrası","Divan edebiyatı","C"),
("'Akış bilinci' tekniği nedir?","Üçüncü şahıs anlatımı","Karakterin iç ses ve düşünce akışının kesintisiz aktarılması","Diyalog tekniği","Geri dönüş tekniği","B"),
("Türkçede 'edilgen çatı' nedir?","Özne eylemi yapar","Özne eylemin yapılışından etkilenir","Özne yok","Fiil bitmez","B"),
("'Postmodern edebiyat'ın özelliği nedir?","Gerçekçilik","Farklı anlatı türlerinin bir arada kullanılması, metinlerarasılık","Milliyetçi temalar","Dini temalar","B"),
("'Aliterasyon' nedir?","Ünlü tekrarı","Aynı sessiz harfin tekrarı","Uyak","Redif","B"),
("Türkçede 'işteş çatı' ne anlama gelir?","Tek kişi","Öznenin birlikte ya da karşılıklı eylemi gerçekleştirmesi","Edilgen eylem","Etken eylem","B"),
("'Montaj tekniği' yazında ne demektir?","Uzun anlatım","Farklı zaman ve mekânlardan sahnelerin bir araya getirilmesi","Diyalog tekniği","Tasvir","B"),
("Türkçede cümle türleri arasında 'devrik cümle' ne demektir?","Yüklem başta","Yüklem sonda","Yüklem ortada","Özne yok","A"),
("'Arketip' kavramı edebiyatta ne demektir?","Yeni bir karakter","Tüm insanlığa ait evrensel simge ve karakter tipleri","Türk edebiyatına özgü karakter","Fantastik karakter","B"),
("Ömer Seyfettin'in edebi türü nedir?","Roman","Şiir","Hikaye","Deneme","C"),
("'Sembolist şiir' akımı nerede doğmuştur?","İngiltere","Türkiye","Fransa","Amerika","C"),
("'Nesnel eleştiri' nedir?","Duygusal ve kişisel yargı","Kanıtlanabilir bilgiye dayalı yargı","Öznel yorum","Tahmin","B"),
("'Ironi' (alaycılık) hangi edebi sanatla ilgilidir?","Benzetme","Söylenenin tersini kastetme","Abartma","Kişileştirme","B"),
("Türk edebiyatında 'Milli Edebiyat akımı' ne zaman başlar?","1860","1896","1911","1923","C"),
("'Parantez içi alıntı' nedir?","Dipnot","Metin içinde kaynak gösterme","Kaynakça","Özet","B"),
("'Çağdaş Türk edebiyatı' için hangi yazar örnek verilebilir?","Fuzuli","Nedim","Orhan Pamuk","Evliya Çelebi","C"),
("'Karşıtlık sanatı' hangisidir?","Teşbih","Tezat","Kişileştirme","Mübalağa","B"),
("Türkçede 'söz dizimi' (sentaks) nedir?","Sözcüklerin anlamı","Cümlelerin yapısını ve sözcüklerin sıralanışını inceleyen dal","Ses bilgisi","Yazım kuralları","B"),
("Makale türünün temel özelliği nedir?","Hayal ürünü","Kanıtlanmış bilgi ve tartışma sunma","Yalnızca fikir","Roman","B"),
("'Geçmişe dönüş' (flashback) ne anlama gelir?","İleriye atlama","Anlatıda geçmişe geri dönme tekniği","Anlatıcı değişimi","Karakter değişimi","B"),
("Türkçede 'eylem bildirmeyen sözcük' nedir?","Fiil","Ad (isim)","Zarf","Bağlaç","B"),
("'Betimleyici anlatım' amacı nedir?","Tartışmak","Bir kişi, yer ya da nesneyi canlandırmak","Bilgi vermek","Öykülemek","B"),
("Atatürk'ün dil devrimi neden yapılmıştır?","Yabancı dilleri yaymak","Türkçeyi yabancı etkilerden arındırmak ve geliştirmek","Arapçayı yaymak","Türkçeyi ortadan kaldırmak","B"),
("'İmge' (imaj) nedir?","Fiziksel görüntü","Şiirde oluşturulan zihinsel resim ya da duygu","Sesli harfler","Roman bölümü","B"),
("'Mizah yazısı' (komedi) neden önemlidir?","Sadece eğlence","Toplumsal eleştiri ve farkındalık aracı","Sadece anlatı","Sadece öğretim","B"),
("'Öyküleme' nedir?","Bir nesneyi tasvir","Olayları anlatan anlatım türü","Duygusal anlatım","Tartışma","B"),
("'Aforizma' nedir?","Uzun şiir","Kısa, derin ve özlü düşünce","Roman bölümü","Diyalog","B"),
("'Ön yargısız okuma' ne demektir?","Okumamak","Metni önceki yargılardan bağımsız, açık bir zihinle okumak","Eleştirel okuma","Hızlı okuma","B"),
("Türk edebiyatında 'toplumcu gerçekçi' yazar hangisidir?","Fuzuli","Namık Kemal","Fakir Baykurt","Nedim","C"),
("'Anlatı perspektifi' ne demektir?","Romanın uzunluğu","Bir hikayenin anlatıldığı bakış açısı","Karakterlerin sayısı","Olayların hızı","B"),
("'Yinelemeli yapı' edebiyatta ne anlama gelir?","Tek seferlik olay","Bir yapının ya da motifin metinde tekrarlanması","Bölüm sonrası sıfırlama","Kronolojik sıra","B"),
("Türkçede 'Bileşik cümle' nedir?","Tek yüklem","Temel ve yan cümleden oluşan cümle","Birbirsiz cümleler","Yüklemsiz cümle","B"),
],

"Matematik": [
("İkinci dereceden denklem ax² + bx + c = 0 olursa diskriminant nedir?","b² - 4ac","b² + 4ac","4ac - b²","b - 4ac","A"),
("Karekök denklemde √x = 3 ise x = ?","6","9","3","27","B"),
("a = 2, b = -3 ise a³ - b² = ?","8 - 9 = -1","8 + 9 = 17","8 - 9 = -1","8 × 9","A"),
("Faktöriyel: 5! = ?","60","100","120","20","C"),
("Geometri: Düzgün beşgenin iç açıları toplamı kaçtır?","360°","540°","720°","900°","B"),
("Daire dilimi alan formülü nedir?","(n/360) × πr²","πr²","2πr","n × r²","A"),
("Veri serisinde standart sapma ne ölçer?","Ortalama","Verilerin ortalamadan ne kadar saptığı","Toplam","Medyan","B"),
("Üçgenlerin benzer olması için hangisi yeterlidir?","Üç kenar eşit","Açı-Açı (AA) benzerlik","İki kenar eşit","Yalnızca çevre","B"),
("Üslü ifade: (2x²)³ = ?","6x⁶","8x⁶","8x⁵","6x⁵","B"),
("Fonksiyon: f(x) = x² - 3x + 2 için f(0) = ?","0","2","4","-2","B"),
("Doğrunun eğimi m = Δy/Δx formülüdür; (1,2) ve (3,6) noktalarından geçen doğrunun eğimi?","1","2","3","4","B"),
("Polinomlar: (x + 2)(x - 3) = ?","x² - x - 6","x² + x - 6","x² - 6","x² - 5x + 6","A"),
("Dizilerde aritmetik dizi: a₁ = 3, d = 4 ise a₅ = ?","16","19","17","23","B"),
("Olasılık: 52 kartlık desteden as çekme olasılığı?","1/13","4/52 = 1/13","1/4","Her ikisi A ve B","D"),
("Koordinat: y = 2x + 1 doğrusunun y-kesim noktası?","(0,2)","(0,1)","(1,0)","(2,0)","B"),
("Türev nedir?","Bir fonksiyonun integrali","Bir fonksiyonun değişim hızı","Fonksiyon değeri","Toplam","B"),
("Mutlak değer: |x - 3| = 5 denkleminin çözüm kümesi?","x = 8","x = -2","x = 8 veya x = -2","x = 2","C"),
("Geometrik dizi: a₁ = 2, r = 3 ise a₄ = ?","54","18","27","36","A"),
("Permütasyon: 5 nesnenin 3'ünü sırayla seçme sayısı (P(5,3)) = ?","10","60","20","120","B"),
("Kombinasyon: C(5,2) = ?","10","20","5","15","A"),
("Trigonometri: sin 30° = ?","√3/2","1/2","1","√2/2","B"),
("cos 60° = ?","√3/2","1","0","1/2","D"),
("Dikdörtgen koordinatlar: (3,4) noktasının orijine uzaklığı?","3","4","5","7","C"),
("İki bilinmeyenli denklem: 2x + y = 10 ve x - y = 2 çözümü?","x=4, y=2","x=3, y=4","x=5, y=0","x=2, y=6","A"),
("Üçgen çeşitleri: Kosinüs teoremi c² = a² + b² - 2ab cosC ifadesi nedir?","Pisagor","Kosinüs teoremi","Sinüs teoremi","Kafiye","B"),
("Kümeler: A = {1,2,3}, B = {2,3,4} ise A ∩ B = ?","{1,2,3,4}","{2,3}","{1,4}","{}","B"),
("Sayma ilkesi: 3 takım elbise ve 4 gömlek varsa kaç kombinasyon?","7","12","8","10","B"),
("Dörtgenler: Eşkenar dörtgenin köşegenleri birbirini nasıl keser?","Eşit parçalar","Dik açıyla (90°)","Paralel","Kesişmez","B"),
("Parabol: y = x² - 4x + 3 in tepe noktası x koordinatı = ?","1","2","3","4","B"),
("İstatistik: 5 sayının ortalaması 8 ise toplamları kaçtır?","40","45","35","48","A"),
("Logaritma: log₁₀ 1000 = ?","2","3","4","5","B"),
("Rasyonel ifade: (x²-4)/(x+2) basit hali nedir?","x-2","x+2","x²","x","A"),
("Vektör: (3,4) vektörünün büyüklüğü?","5","7","3","4","A"),
("Matris çarpımı 2×2: [[1,2],[3,4]] × [[2,0],[1,3]] ilk satır, ilk sütun elemanı?","4","2","5","8","A"),
("İkinci derece: x² = 16 denkleminin çözümleri?","x = 4","x = -4","x = 4 veya x = -4","x = 8","C"),
],

"Fen Bilimleri": [
("DNA'nın temel yapı birimi hangisidir?","Protein","Aminoasit","Nükleotid","Şeker","C"),
("Genler nerede bulunur?","Sitoplazma","Mitokondri","DNA'da, kromozomlar üzerinde","Hücre zarı","C"),
("Mendel'in kalıtım kanunları kaç temel ilke içerir?","1","2","3","4","B"),
("Mutasyon nedir?","Protein değişimi","DNA dizisindeki kalıcı değişiklik","Hücre bölünmesi","Kromozom sayısı","B"),
("Periodik tablodaki elementler hangi bilgiyle numaralandırılır?","Kütle numarası","Atom numarası","Nötron sayısı","Elektron ağırlığı","B"),
("Kimyasal bağ türleri nelerdir?","Yalnızca iyonik","İyonik, kovalent, metalik","Yalnızca kovalent","Hidrojen ve zayıf","B"),
("Mol kavramı nedir?","Madde miktarı birimi (6,02×10²³ tanecik)","Kütle birimi","Hacim birimi","Enerji birimi","A"),
("Enerji dönüşümlerinde ilk yasa ne der?","Enerji artabilir","Enerji yok edilemez, yalnızca dönüşür","Enerji azalabilir","Enerji sabit kalır","B"),
("Elektromanyetik spektrumda görünür ışık nerededir?","Radyasyonun altında","Kızılötesi ve morötesi arasında","Gamma ışınlarından büyük","X ışınlarından küçük","B"),
("Biyolojide 'homeostasis' ne demektir?","Hücre bölünmesi","Organizma içindeki iç dengenin korunması","Fotosentez","Mutasyon","B"),
("Kimya: Asit kuvveti neyle belirlenir?","Konsantrasyonuyla","pH değeriyle (düşük pH kuvvetli asit)","Rengiyle","Hacmiyle","B"),
("Kütlenin korunumu yasası kime aittir?","Newton","Lavoisier","Einstein","Dalton","B"),
("Atom çekirdeği hangi parçacıklardan oluşur?","Proton ve elektron","Nötron ve elektron","Proton ve nötron","Yalnızca proton","C"),
("'Eşik frekans' kavramı hangi olayda geçer?","Fotoelektrik olay","Manyetik rezonans","Nükleer fisyon","Alfa çöküşü","A"),
("Dönme kinetik enerjisi formülü nedir?","½mv²","½Iω²","mgh","PV","B"),
("Dalga boyu ve frekans ilişkisi nedir?","λ = v × f","v = λ × f","f = v + λ","v = f / λ","B"),
("Canlılarda enerji para birimi olarak ne kullanılır?","AMP","ADP","ATP","NAD","C"),
("İnsan vücudunda hangi organ insülin üretir?","Karaciğer","Böbrek","Pankreas","Dalak","C"),
("'Redoks reaksiyonu' nedir?","Yalnızca asit-baz","Elektron transferini içeren reaksiyon","Isı üretimi","Işık üretimi","B"),
("Fisson ve füzyon farkı nedir?","Fisson birleşme, füzyon bölünmedir","Fisson bölünme (ağır çekirdek), füzyon birleşme (hafif çekirdek)","İkisi aynıdır","Fark yok","B"),
("Biyokimyada enzim ne yapar?","Ürün oluşturur","Reaksiyon hızını artırır (katalizör)","Enerji depolar","DNA sentezler","B"),
("Yıldızlar enerjilerini hangi yolla üretir?","Fisyon","Füzyon (nükleer birleşme)","Kimyasal yanma","Elektrik","B"),
("Yarı iletkenler neden önemlidir?","Yalnızca ısıya","Elektronik devrelerde transistör vb. kullanımı","Yalnızca kimyaya","Yalnızca biyolojiye","B"),
("'Biyoçeşitlilik' neden önemlidir?","Yalnızca güzellik için","Ekosistem stabilitesi ve canlı kaynakları için","Yalnızca araştırma","Yalnızca turizm","B"),
("İnsan bağışıklık sisteminde 'antijen' ne demektir?","Bağışıklık hücresi","Bağışıklık sistemini tetikleyen yabancı madde","Antikor","Protein","B"),
("Evrenin büyüklüğü nasıl ölçülür?","Kilometreyle","Işık yılıyla","Fersahla","Metreyle","B"),
("Kimyasal denge ne demektir?","Reaksiyon durur","İleri ve geri reaksiyon hızlarının eşitlenmesi","Ürünler kaybolur","Reaktantlar bitmez","B"),
("'Ozon tabakası' neden önemlidir?","Su sağlar","Güneşten gelen zararlı UV ışınlarını filtreler","Oksijen üretir","Isı tutar","B"),
("Genetik mühendislik nedir?","Doğal üreme","Organizmaların DNA'sını değiştirme tekniği","Klonlama yöntemi","İlaç üretimi","B"),
("'Astrofizik' nedir?","Jeoloji","Fizik yasalarını gök cisimlerine uygulayan bilim","Kimya","Biyoloji","B"),
("İnsan vücudunun en büyük organı nedir?","Karaciğer","Beyin","Deri","Bağırsak","C"),
("Fotoelektrik olay neyi kanıtlar?","Işığın dalga niteliği","Işığın tanecik (foton) niteliği","Ses hızı","Nükleer reaksiyon","B"),
("'Kataliz' ne demektir?","Reaksiyonu durdurmak","Reaksiyon hızını değiştirmek (katalizör kullanımı)","Ürün oluşturmak","Reaktant eklemek","B"),
("'Polimer' nedir?","Küçük molekül","Tekrarlayan birimlerden oluşan büyük molekül","Atom","İyon","B"),
("Kalıtsal hastalıklara örnek hangisidir?","Grip","Orak hücreli anemi","Nezle","Tifo","B"),
],

"T.C. İnkılap Tarihi": [
("Kurtuluş Savaşı'nın başlangıç tarihi kabul edilen olay nedir?","Lozan Antlaşması","Samsun'a çıkış (19 Mayıs 1919)","TBMM'nin açılması","Mudanya Mütarekesi","B"),
("Misak-ı Millî ne anlama gelir?","Osmanlı'nın devamı","Türk milletinin vazgeçilmez ulusal sınırları","Barış antlaşması","Yeni hükümet","B"),
("Türkiye Büyük Millet Meclisi hangi tarihte açılmıştır?","19 Mayıs 1919","23 Nisan 1920","29 Ekim 1923","30 Ağustos 1922","B"),
("Büyük Taarruz hangi yıl gerçekleşmiştir?","1919","1920","1921","1922","D"),
("Sakarya Meydan Muharebesi ne zaman yaşanmıştır?","1919","1920","1921","1922","C"),
("Lozan Antlaşması hangi yılda imzalanmıştır?","1920","1921","1922","1923","D"),
("Cumhuriyet hangi tarihte ilan edilmiştir?","23 Nisan 1920","30 Ağustos 1922","29 Ekim 1923","3 Mart 1924","C"),
("İlk Türk anayasası hangi yılda kabul edilmiştir?","1920","1921","1923","1924","D"),
("Halifelik hangi yıl kaldırılmıştır?","1922","1923","1924","1925","C"),
("Harf İnkılabı hangi yılda gerçekleşmiştir?","1923","1924","1925","1928","D"),
("Atatürk'ün soyadı olan 'Atatürk' hangi kanunla verilmiştir?","Kıyafet Kanunu","Soyadı Kanunu (1934)","Harf Devrimi","Medeni Kanun","B"),
("Türkiye'de kadınlara milletvekili seçilme hakkı hangi yılda tanınmıştır?","1923","1930","1934","1940","C"),
("İzmir Suikastı girişimi hangi yılda olmuştur?","1926","1924","1928","1930","A"),
("'Tekalif-i Milliye' emirleri ne için çıkarıldı?","Vergi toplamak","Halkın orduya katkı sağlaması için","Yargı reformu","Okul açmak","B"),
("Sevr Antlaşması hangi taraflarca imzalanmıştır?","Türkiye ve Fransa","Osmanlı Devleti ve İtilaf devletleri","Türkiye ve Yunanistan","Türkiye ve Rusya","B"),
("Kuvva-yı Milliye nedir?","Düzenli ordu","Millî Mücadele'nin başlarında oluşturulan düzensiz direniş kuvvetleri","İstanbul hükümeti","Yunan kuvvetleri","B"),
("Ankara'nın başkent ilan edildiği yıl?","1920","1922","1923","1924","C"),
("İstiklal Marşı'nın şairi kimdir?","Ziya Gökalp","Mehmet Akif Ersoy","Yahya Kemal","Tevfik Fikret","B"),
("Millî Mücadele'de İngilizlere karşı verilen Pontus mücadelesi nerede yaşandı?","Ege","Karadeniz","İç Anadolu","Trakya","B"),
("Atatürk'ün 'Nutuk' eseri hangi konuyu anlatır?","Roman","1919-1927 yılları arasındaki Kurtuluş Savaşı ve Cumhuriyet'in kuruluşu","Şiir","Matematik","B"),
("İlk Türk kadın avukat kim olarak kabul edilir?","Sabiha Gökçen","Türkan Saylan","Süreyya Ağaoğlu","Halide Edip","C"),
("Doğu Cephesi'nde Kazım Karabekir'in savaştığı ülke hangisidir?","Yunanistan","İngiltere","Ermenistan","Fransa","C"),
("Türkiye'de çok partili hayata geçiş ne zaman olmuştur?","1923","1930","1945","1950","D"),
("Atatürk hangi yılda vefat etmiştir?","1936","1937","1938","1939","C"),
("'Tam Bağımsızlık' ilkesi neyi ifade eder?","Ekonomik bağımsızlık","Her alanda yabancı egemenliğini reddetmek","Askeri güç","Dış yardım","B"),
("Kurtuluş Savaşı'nda Batı Cephesi komutanı kimdir?","Kazım Karabekir","İsmet İnönü","Ali Fuat Cebesoy","Refet Bele","B"),
("Nüfus mübadelesi hangi antlaşmayla gerçekleşmiştir?","Sevr","Lozan","Mondros","Mudanya","B"),
("Türkiye'de laik eğitim ne zaman başladı?","1923","1924","1931","1928","B"),
("Medeni Kanun hangi ülkenin hukukundan uyarlanmıştır?","Fransa","İngiltere","İsviçre","Almanya","C"),
("Atatürk dönemi inkılapları için 'devrimci' niteliği neden önemlidir?","Yavaş değişim","Toplumun her alanını kısa sürede köklü biçimde dönüştürmesi","Sadece ekonomik","Sadece siyasi","B"),
("Birinci Dünya Savaşı'nda Osmanlı'nın yenilmesinin sonucu nedir?","Osmanlı güçlendi","Mondros Mütarekesi ve toprakların işgale açılması","Ekonomi gelişti","Osmanlı genişledi","B"),
("İstanbul'un işgali hangi yılda gerçekleşti?","1918","1919","1920","1921","C"),
("Atatürk'ün kurduğu ilk siyasi parti hangisidir?","Cumhuriyet Halk Fırkası","Demokrat Parti","Terakkiperver Cumhuriyet Fırkası","Serbest Cumhuriyet Fırkası","A"),
("Kıbrıs Cumhuriyeti hangi yılda kurulmuştur?","1950","1960","1970","1980","B"),
("TBMM tarafından onaylanan ilk bütçe hangi yıla aittir?","1921","1922","1923","1924","A"),
],

"İngilizce": [
("What does 'sustainable' mean?","geçici","sürdürülebilir","pahalı","modern","B"),
("'The project ___ (had been completed/has been completed/was completed) before the deadline.'","has been completed","was being completed","is completed","had been completed","D"),
("What does 'consequence' mean?","sebep","sonuç","durum","önem","B"),
("'She ___ (must have left/must leave/should leave) early — the door is locked.'","must leave","should leave","might leave","must have left","D"),
("What does 'approximately' mean?","kesinlikle","yaklaşık","tamamen","asla","B"),
("'No sooner ___ he arrived than it started raining.' (had/did/has)","did","has","is","had","D"),
("What does 'allocate' mean?","tahsis etmek","toplamak","dağıtmak","toplamak","A"),
("'The results ___ (are being analyzed/will analyze/analyzed) by scientists.'","analyzed","will analyze","have analyzed","are being analyzed","D"),
("What does 'sophisticated' mean?","basit","karmaşık, sofistike","ucuz","eski","B"),
("'I would have called you if I ___ (had known/have known/knew) earlier.'","have known","knew","know","had known","D"),
("What does 'deteriorate' mean?","iyileşmek","kötüleşmek","büyümek","değişmek","B"),
("'He is considered ___ (to be/being/be) one of the best.'","being","be","been","to be","D"),
("What does 'emphasize' mean?","küçümsemek","vurgulamak","açıklamak","eleştirmek","B"),
("'By the time they ___ (arrived/arrive/had arrived), we had finished.'","had arrived","arrive","arriving","arrived","D"),
("What does 'inevitable' mean?","önlenebilir","kaçınılmaz","olası","beklenmedik","B"),
("'She ___ (is said to be/says to be/said to be) an expert.'","says to be","said to be","saying to be","is said to be","D"),
("What does 'advocate' mean?","savunmak, desteklemek","eleştirmek","reddetmek","ihmal etmek","A"),
("'The more you practice, ___ you become.' (the better/better/best)","better","best","the best","the better","D"),
("What does 'fundamental' mean?","önemsiz","temel, esas","basit","karmaşık","B"),
("'I'd rather you ___ (didn't smoke/don't smoke/not smoke) here.'","don't smoke","not smoke","not smoking","didn't smoke","D"),
("What does 'comprehensive' mean?","kısmi","kapsamlı","belirsiz","yüzeysel","B"),
("'He ___ (is reported to have stolen/reports to steal/reported stealing) the money.'","reports to steal","reported stealing","reported to steal","is reported to have stolen","D"),
("What does 'ambiguous' mean?","net","belirsiz, çift anlamlı","basit","açık","B"),
("'Not until she arrived ___ (did he leave/he left/he leave).'","he left","he leave","he had left","did he leave","D"),
("What does 'acknowledge' mean?","inkar etmek","kabul etmek, onaylamak","görmezden gelmek","eleştirmek","B"),
("'She suggested ___ (that we should try/to try/us trying) a different approach.'","to try","us trying","trying","that we should try","D"),
("What does 'obsolete' mean?","yeni","modaya uygun","modası geçmiş","popüler","C"),
("'Were I in your position, I ___ (would do/will do/did) the same.' (advanced conditional)","will do","did","would have done","would do","D"),
("What does 'transparent' mean?","opak","şeffaf, açık","karanlık","kapalı","B"),
("'The suspect is alleged ___ (to have committed/of committing/that he committed) the crime.'","of committing","that he committed","committing","to have committed","D"),
("What does 'legitimate' mean?","yasadışı","meşru, yasal","gizli","tehlikeli","B"),
("'Hardly ___ (had she spoken/she had spoken/did she speak) when the alarm went off.'","she had spoken","did she speak","has she spoken","had she spoken","D"),
("What does 'perseverance' mean?","tembellik","azim, ısrarlı devam","korku","şüphe","B"),
("'The building ___ (is scheduled to be renovated/schedules to renovate/will renovate) next year.'","schedules to renovate","will renovate","has renovated","is scheduled to be renovated","D"),
("What does 'eloquent' mean?","söz ustalığı olan, belagatli","suskun","kaba","yavaş","A"),
],

"Din Kültürü": [
("İslam medeniyetinin bilime katkıları arasında hangisi sayılabilir?","Sadece cami mimarisi","Matematik, astronomi, tıp, kimya gibi alanlardaki çalışmalar","Sadece şiir","Sadece savaş","B"),
("'Usul-u Fıkıh' nedir?","İslam tarihinin anlatıldığı dal","İslam hukukunun kaynaklarını ve yöntemlerini inceleyen ilim","Kelam","Tasavvuf","B"),
("İslam'daki 'icma' kavramı ne demektir?","Bir kişinin görüşü","Müçtehitlerin bir meselede fikir birliği","Kur'an hükmü","Hadis","B"),
("'Kıyas' İslam hukukunda nedir?","Yeni olayları Kur'an ve Sünnete dayanarak benzer meseleye kıyaslama","Hadis toplama","Tefsir yazma","Namaz vakti","B"),
("İslam dünyasında bilim ve felsefenin altın çağı hangi dönemdir?","Dört Halife dönemi","Abbasiler dönemi","Osmanlı dönemi","Emeviler dönemi","B"),
("'Tasavvuf' nedir?","İslam hukuku","İslam'da ruhani arınma ve Allah'a yaklaşmayı hedefleyen gönül yolu","Kelam ilmi","Tefsir","B"),
("Maturidilik ve Eş'arilik hangi ilmin kollarıdır?","Fıkıh","Kelam (İslam inancını akıl ve nakille temellendiren ilim)","Hadis","Tasavvuf","B"),
("Ahlak felsefesinde 'erdem' ne demektir?","Maddi zenginlik","İyi bir karakter ve doğru davranışların alışkanlığa dönüşmesi","Zeka","Cesaret yalnız","B"),
("İslam dünyasında 'vakıf' neden gelişmiştir?","Vergi toplamak için","Eğitim, sağlık ve sosyal hizmetleri finanse etmek için","Askeri güç","Siyasi güç","B"),
("'Zahir' ve 'batın' kavramları tasavvufta ne anlama gelir?","İki peygamber","Dış (zahir) ve iç (batın) boyut","İki sure","İki mezhep","B"),
("Şiilikte 'imametin' önemi nedir?","Yalnızca İslam hukuku","Hz. Ali ve onun soyundan gelen imamlara itaatin dini zorunluluk sayılması","Sünnet","Hac","B"),
("'Ahlak-ı Hamide' ne demektir?","Kötü ahlak","Övgüye değer, erdemli ahlak","Orta ahlak","Yüzeysel ahlak","B"),
("İmam Gazali'nin en önemli eseri hangisidir?","Fatiha Tefsiri","İhyau Ulumiddin","Divan","Mesnevi","B"),
("'Nefis terbiyesi' neden önemlidir?","Fiziksel güç","Kişinin kötü eğilimlerini kontrol edip erdemleri geliştirmesi","Sadece ibadet","Yalnızca eğitim","B"),
("'Dini hoşgörü' İslam'da nasıl ifade edilir?","Zorla din değiştirme","'Dinde zorlama yoktur' (Bakara 256) ilkesi","Sadece Müslümanlara saygı","Yabancılara baskı","B"),
("Osmanlı'da müftü kimdir?","Vergi toplayan kişi","İslam hukuku konusunda fetva veren yetkili","Cami imamı","Okul müdürü","B"),
("İslam'da 'şura' (danışma) ilkesinin yönetimde önemi nedir?","Baskıcı yönetim","İstişareyle yönetimin demokratik ve adaletli olması","Sadece ekonomi","Askeri karar","B"),
("'Hilafet' sistemi nedir?","Krallık","Hz. Muhammed'den sonra İslam toplumuna önderlik eden kurum","Cumhuriyet","Monarşi","B"),
("İslam bilim tarihinde El-Harezmi kimin adıdır?","Coğrafyacı","Matematik (cebir) ve algoritmanın babası sayılan alim","Hekim","Şair","B"),
("'Sosyal adalet' İslam'da nasıl ele alınır?","Yalnızca ibadet","Zengin ve fakir arasındaki dengenin zekât, sadaka vb. yollarla korunması","Yalnızca ekonomi","Siyasi güç","B"),
("'İttihad-ı İslam' fikri ne anlama gelir?","Müslümanların ayrılması","Dünya Müslümanlarının birlik ve dayanışması","Osmanlı yenilenmesi","Dini devlet","B"),
("'Müçtehit' ne demektir?","Her Müslüman","Kur'an ve Sünnet'ten hüküm çıkaran derinlikli ilim sahibi alim","Cami görevlisi","Vaiz","B"),
("Kur'an'ı Kerim'in derlenmesi hangi halife döneminde tamamlanmıştır?","Hz. Ebubekir","Hz. Ömer","Hz. Osman","Hz. Ali","C"),
("'İttifak' ve 'ihtilaf' arasındaki dini denge nedir?","Her zaman mutabık olmak","Temel konularda birlik, feri (ayrıntı) konularda farklı görüşe saygı","Her zaman ayrılık","Görüşsüz kalmak","B"),
("İslam ahlakında 'infak' ne demektir?","İbadetten kaçmak","Allah yolunda harcamak, vermek","Tasarruf","Varlık biriktirmek","B"),
("'Bid'at' ne demektir?","Sünnet","Dinde olmayan yeni uygulamaları dine dahil etme girişimi","İcma","Kıyas","B"),
("İbn Haldun kimdir ve neyle tanınır?","Hekim","Sosyoloji ve tarih felsefesinin öncüsü sayılan İslam alimi","Şair","Müzisyen","B"),
("'Şeriat' kapsamlı anlamda nedir?","Yalnızca ceza","İslam'ın ibadet, muamelat ve ahlak gibi kapsamlı hukuki-ahlaki düzeni","Yalnızca namaz","Yalnızca oruç","B"),
("'İman-ı tahkiki' ne demektir?","Körü körüne inanç","Araştırarak ve anlayarak kazanılan inanç","Taklit","Şüpheli inanç","B"),
("Atatürk döneminde laikleşme süreci din eğitimini nasıl etkiledi?","Değiştirmedi","Din eğitimi devlet denetiminde yeniden düzenlendi","Tamamen kaldırıldı","Arttırıldı","B"),
("'Sadaka-i câriye' ne anlama gelir?","Bir defaya mahsus yardım","İnsandan öldükten sonra da devam eden faydalı hayır","Zekât","Hac","B"),
("'Mütevazılık' neden önemlidir?","Güç göstergesi","Allah'a ve insanlara karşı alçakgönüllülük erdemi","Zayıflık","Çekingenlik","B"),
("'Fıkhi mezheplerin' oluşmasının temel nedeni nedir?","Kur'an farklılıkları","Nassların (kaynak metinlerin) yorumlanmasındaki farklı yöntemler","Siyasi ayrılık","Coğrafi farklılık","B"),
("İslam'da 'hakkaniyet' ilkesi neden önemlidir?","Güçlüyü desteklemek","Herkese durumuna göre adil muamele etmek","Eşit paylaşım","Kanun","B"),
("Son peygamber Hz. Muhammed'in risaletinin evrenselliği ne anlama gelir?","Yalnızca Araplara","Kıyamete kadar tüm insanlığa gönderilmiş olması","Yalnızca Müslümanlara","Yalnızca Arap yarımadasına","B"),
],

}, # end of grade 8

} # SORULAR

def tum_sorular_as_list() -> list[dict]:
    """Tüm soruları veritabanına eklenebilir düz liste olarak döner."""
    rows = []
    sira = 1
    for sinif_no, dersler in SORULAR.items():
        for ders_adi, sorular in dersler.items():
            for s in sorular:
                rows.append({
                    "sinif_seviyesi": sinif_no,
                    "ders":           ders_adi,
                    "soru":           s[0],
                    "secenek_a":      s[1],
                    "secenek_b":      s[2],
                    "secenek_c":      s[3],
                    "secenek_d":      s[4],
                    "dogru_cevap":    s[5],
                    "sira":           sira % 35 + 1,  # 1-35 döngüsü
                })
                sira += 1
    return rows
