import assert from 'node:assert/strict';
import {BroadcastPlayback} from '../static/school-broadcast-playback.mjs';
let time=0;
const player=new BroadcastPlayback(()=>time);
player.loading();time=12000;
assert.equal(player.due(),false,'A slow page must not be skipped before it is visible');
player.visible();time=16999;assert.equal(player.due(),false);
time=17000;assert.equal(player.due(),true,'Slide advances at five seconds');
player.loading();time=25000;assert.equal(player.due(),false);
player.visible();time=27000;player.setPaused(true);
time=100000;assert.equal(player.due(),false,'Pause must survive arbitrary elapsed time');
player.setPaused(false);time=102999;assert.equal(player.due(),false);
time=103000;assert.equal(player.due(),true,'Resume keeps the three seconds remaining');
player.videoProgress();time=120000;player.videoProgress();time=135000;
assert.equal(player.due(),false,'A playing video is not cut at five seconds');
time=140000;assert.equal(player.due(),true,'A stalled video releases the playlist');
player.failed();time=144999;assert.equal(player.due(),false);
time=145000;assert.equal(player.due(),true,'An error does not leave the playlist stuck');
player.setPaused(true);player.loading();player.visible();time=200000;
assert.equal(player.due(),false);player.setPaused(false);time=205000;
assert.equal(player.due(),true,'Content loaded during pause still receives five seconds');
console.log('PASS: five-second timing, delayed loading, pause/resume, video and error recovery');
