import assert from 'node:assert/strict';
import {BroadcastPlayback} from '../static/school-broadcast-playback.mjs';
let time=0;
const player=new BroadcastPlayback(()=>time);
player.loading();time=12000;
assert.equal(player.due(),false,'A slow page must not be skipped before it is visible');
player.visible();time=16999;assert.equal(player.due(),false);
time=17000;assert.equal(player.due(),true,'Slide advances at five seconds');
player.loading();time=25000;assert.equal(player.due(),false);
player.visible();time=27000;player.setPaused(true);
time=100000;assert.equal(player.due(),false,'Pause must survive arbitrary elapsed time');
player.setPaused(false);time=102999;assert.equal(player.due(),false);
time=103000;assert.equal(player.due(),true,'Resume keeps the three seconds remaining');
player.videoProgress();time=120000;player.videoProgress();time=135000;
assert.equal(player.due(),false,'A playing video is not cut at five seconds');
time=140000;assert.equal(player.due(),true,'A stalled video releases the playlist');
player.failed();time=144999;assert.equal(player.due(),false);
time=145000;assert.equal(player.due(),true,'An error does not leave the playlist stuck');
player.setPaused(true);player.loading();player.visible();time=200000;
assert.equal(player.due(),false);player.setPaused(false);time=205000;
assert.equal(player.due(),true,'Content loaded during pause still receives five seconds');
player.setDuration(10);player.loading();time=230000;
assert.equal(player.due(),false,'Loading does not use up the selected interval');
player.visible();time=239999;assert.equal(player.due(),false);
time=240000;assert.equal(player.due(),true,'A ten-second slide receives the full interval');
player.visible();time=243000;player.setPaused(true);time=300000;
assert.equal(player.due(),false);player.setPaused(false);time=306999;
assert.equal(player.due(),false);time=307000;
assert.equal(player.due(),true,'Resume keeps seven seconds of a ten-second interval');
player.setDuration(5);player.visible();time=311999;assert.equal(player.due(),false);
time=312000;assert.equal(player.due(),true,'The next file can select five seconds independently');
player.setDuration(300);assert.equal(player.duration,5,'Unsupported old intervals use the default');
console.log('PASS: selectable five/ten-second timing, delayed loading, pause/resume, video and error recovery');
